<?php
  // module/lab/view/application/index/auto-suggest.phtml
  if ($this->searchEleNo == '') {
    $this->searchEleNo = 0;
  }
  $limit = $this->limit;
  $pages = 0;
  $limitEnd	= $limit;
  $rows = $this->result['rowCount'];
	if ($this->page == '' || $this->page == 0) {
		$limitStart = 0;
	} else {
		$limitStart = $this->page;
	}
  $pages = ceil($rows / $limit);
  if ($rows >= 1 && round($rows / $limit) == 0) {
			$pages = 1;
		} else {
			$pages = round($rows / $limit) + 1;
	}
  $id = 6;
?>
<style>
  .selected_item {
    background-color: #E0ECFF;
    border: 1px solid #d9d9d9;
    cursor: default;
    display: block;
    height: 20px;
    white-space: nowrap;
    -webkit-border-radius: 3px;
    border-radius: 3px; 
    margin: 1.2px;
    float: left;
    font-size: 12px;
    text-align: center;
  }
  
  .selected_item:hover {
    border: thin solid #FFAFAF;
  }
  
  .close {
    /*float: right;*/
    padding-left: 5px; 
    color: #f00;
    cursor:pointer;
  }
}
</style>
<div class="panel_content_wrapper">
<div class="panel-head">
  <div class="top_panel_head">
    <span style="padding-left:20px;">
    <?php 
    if ($limitStart >= $limit) {
      echo '<a href="javascript:void(0)" style="color: #fff;" onClick="previousPage(' . $this->escapeHtml($limitStart - $limit) . ','. "'" . $this->escapeHtml($this->searchType) . "'" .',' . $this->escapeHtml($this->searchEleNo) . ',' . "'" . $this->escapeHtml($this->searchMode) . "'" . ');" id="previous">' . $this->listenerObject->z_xlt('Previous') . '</a>';
    }
    ?>
    </span>
    <span class="panel-title" style="margin-left:5px; width:105px;"><?php echo $this->listenerObject->z_xlt('Total Records');?>.</span>
    <span><?php echo $this->escapeHtml($rows); ?></span>
    <span class="panel-title" style="padding-left:10px; width:100px;"><?php echo $this->listenerObject->z_xlt('Total Pages');?>.</span>
    <span><?php if ($rows > 0) echo (($limitStart / $limit) + 1) . ' / ' . $pages; ?></span>
  

  <span style="padding-left:20px;">
    <?php 
    /*if ($limitStart >= $limit) {
      echo '<a href="javascript:void(0)" style="color: #fff;" onClick="previousPage(' . ($limitStart - $limit) . ','. "'" . $this->searchType . "'" .',' . $this->searchEleNo . ',' . "'" . $this->searchMode . "'" . ');" id="previous">Previous</a>';
    }
    echo "    ";*/
    if ($limitStart < $rows - $limit) {
      echo '<a href="javascript:void(0)" style="color: #fff;" onClick="nextPage(' . $this->escapeHtml($limitStart + $limit) . ',' . "'" . $this->escapeHtml($this->searchType) . "'" .',' . $this->escapeHtml($this->searchEleNo) . ',' . "'" . $this->escapeHtml($this->searchMode) . "'" . ');" id="next">' . $this->listenerObject->z_xlt('Next') . '</a>';
    }
    ?>
	</span>
</div>
  <div style="clear:both;"></div>
  <div class="bottom_panel_head">
    <div class="itemHead" style="width:30px;"><?php echo $this->listenerObject->z_xlt('Sl.No'); ?></div>
    <div class="itemHead" style="width:232px;"><?php echo $this->listenerObject->z_xlt('NAME'); ?></div>
    <div class="itemHead" style="width:40px;"><?php echo $this->listenerObject->z_xlt('PID'); ?></div>
    <div class="itemHead" style="width:60px;"><?php echo $this->listenerObject->z_xlt('DoB'); ?></div>
    <div style="clear:both;"></div>
  </div>
  
</div>
<div class="panel_content">
  <?php
  //$keywords = str_replace("%", "", $queryString);
  $i = $limitStart + 1;
	$lineNo = 1;
  if ($rows > 0) {
    foreach ($result as $value) : 
      //$name  	= hightlight($value['fname'], $keywords) . ' ' . hightlight($value['lname'], $keywords);
      //$pat_pid 	= hightlight($value['pid'], $keywords);
      //$dob 	= hightlight($value['DOB'], $keywords);
      $name       = $CommonPlugin->hightlight($value['fname'], $keyword) . ' ' . $CommonPlugin->hightlight($value['lname'], $keyword);
      $patient_id = $CommonPlugin->hightlight($value['pid'], $keyword);
      $dob        = $CommonPlugin->hightlight($value['DOB'], $keyword);
      
      //$name         = $value['fname'] . ' ' . $value['lname'];
      //$patient_id 	= $value['pid'];
      //$dob          = $value['DOB'];
      if ($this->searchType == 'patient') {
        $fullName = $value['lname'] . "," . " " . $value['fname'] . " " . $value['mname'];
      }else if ($this->searchType == 'multiplepatient') {
        $fullName = $value['lname'] . "," . " " . $value['fname'];
      }else if ($this->searchType == 'multiplepatientfullname'){
        $fullName = $value['lname'] . "," . $value['mname'] . "," . $value['fname'];
      }
      if (($i % 2) == 1)  { 
        $row = 'row1'; 
      } else if (($i % 2) == 0) {
        $row = 'row2'; 
      }
      ?>
    <div class="panel_row">
      <?php 
        $fill = 'filllist';
      ?>
        <ul tabindex="0" 
            onKeyDown="move(event, '<?php echo $this->escapeHtml($lineNo); ?>', '<?php echo $this->escapeHtml('list_' . $this->searchEleNo); ?>', '<?php echo $this->escapeHtml($this->searchEleNo);?>');" 
            id="<?php echo 'list_' . $this->searchEleNo . '_' . $lineNo; ?>" 
            style="margin:0; padding:0;" 
            class="<?php if ($lineNo == 1) { echo "row"; } else { echo $row;} ?>">
        <li>
      <?php 
        if ($this->searchType == 'patient') { ?>
          <span style="float: left;" 
              id="<?php echo $fill . '_' . $this->searchEleNo . '_' . $lineNo; ?>" 
              onClick='fill("<?php echo $this->escapeHtml($value['fname']) . ' ' . $this->escapeHtml($value['lname']) . '|' . $this->escapeHtml($value['pid']); ?>", "<?php echo $this->escapeHtml($this->searchType); ?>", "<?php echo $this->escapeHtml($this->searchEleNo);?>" , "<?php echo $this->escapeHtml($this->searchMode); ?>");'>
      <?php } ?>
      <div class="itemBox" style="width:30px;"><?php echo $this->escapeHtml($i); ?></div>
      <div class="itemBox" style="width: 232px;height: auto;">
      <?php
        echo $this->listenerObject->z_xlt($name);
      ?>
      </div>
      <div class="itemBox" style="width:40px;"><?php echo $this->escapeHtml($patient_id); ?></div>
      <div class="itemBox" style="width:60px; border-right:none;"><?php echo $dob; ?></div>					
      </li>
      </ul>					
      </span>			
     <div style="clear:both;"></div>
      </div>

      <?php
      $i++;
      $lineNo++;
      if($lineNo >= count($result)) break;
    endforeach;
  }
  ?>
  </div>
</div>
 


