  <?php echo $this->headLink()
    ->prependStylesheet($this->basePath() . '/css/calendar/colorselect.css')
    ->prependStylesheet($this->basePath() . '/css/calendar/dropdown.css')
  ?>
  <?php echo $this->headScript()
    ->prependFile($this->basePath() . '/js/lib/jquery.edatagrid.js')
    ->prependFile($this->basePath() . '/js/calendar/jquery.colorselect.js')
    ->prependFile($this->basePath() . '/js/calendar/jquery.dropdown.js')
    ->prependFile($this->basePath() . '/js/calendar/jquery.validate.js')
    ->prependFile($this->basePath() . '/js/calendar/jquery.form.js')
  ?>

<script>
  if (!DateAdd || typeof (DateDiff) != "function") {
    var DateAdd = function(interval, number, idate) {
      number = parseInt(number);
      var date;
      if (typeof (idate) == "string") {
        date = idate.split(/\D/);
        eval("var date = new Date(" + date.join(",") + ")");
      }
      if (typeof (idate) == "object") {
        date = new Date(idate.toString());
      }
      switch (interval) {
        case "y": date.setFullYear(date.getFullYear() + number); break;
        case "m": date.setMonth(date.getMonth() + number); break;
        case "d": date.setDate(date.getDate() + number); break;
        case "w": date.setDate(date.getDate() + 7 * number); break;
        case "h": date.setHours(date.getHours() + number); break;
        case "n": date.setMinutes(date.getMinutes() + number); break;
        case "s": date.setSeconds(date.getSeconds() + number); break;
        case "l": date.setMilliseconds(date.getMilliseconds() + number); break;
      }
      return date;
    }
  }
  
  function getHM(date) {
    var hour =date.getHours();
    var minute= date.getMinutes();
    var ret= (hour>9?hour:"0"+hour)+":"+(minute>9?minute:"0"+minute) ;
    return ret;
  }
  
  $(document).ready(function() {
    //debugger;
    var DATA_FEED_URL = "php/datafeed.php";
    var arrT = [];
    var tt = "{0}:{1}";
    for (var i = 0; i < 24; i++) {
      arrT.push(
        {text: StrFormat(tt, [i >= 10 ? i : "0" + i, "00"]) }, { text: StrFormat(tt, [i >= 10 ? i : "0" + i, "30"])}
      );
    }
    
    $("#timezone").val(new Date().getTimezoneOffset()/60 * -1);
    $("#stparttime").dropdown({
      dropheight: 200,
      dropwidth:60,
      selectedchange: function() { },
      items: arrT
    });
    $("#etparttime").dropdown({
        dropheight: 200,
        dropwidth:60,
        selectedchange: function() { },
        items: arrT
    });
    var check = $("#IsAllDayEvent").click(function(e) {
      if (this.checked) {
          $("#stparttime").val("00:00").hide();
          $("#etparttime").val("00:00").hide();
      }
      else {
          var d = new Date();
          var p = 60 - d.getMinutes();
          if (p > 30) p = p - 30;
          d = DateAdd("n", p, d);
          $("#stparttime").val(getHM(d)).show();
          $("#etparttime").val(getHM(DateAdd("h", 1, d))).show();
      }
    });
    if (check[0].checked) {
      $("#stparttime").val("00:00").hide();
      $("#etparttime").val("00:00").hide();
    }
    $("#Savebtn").click(function() {alert('tt'); $("#fmEdit").submit(); });
    $("#Closebtn").click(function() { alert('etett');CloseModelWindow(); });
    $("#Deletebtn").click(function() {
      if (confirm("Are you sure to remove this event")) {  
        var param = [{ "name": "calendarId", value: 8}];                
        $.post(DATA_FEED_URL + "?method=remove",
          param,
            function(data){
              if (data.IsSuccess) {
                alert(data.Msg); 
                CloseModelWindow(null,true);                            
              }else {
                alert("Error occurs.\r\n" + data.Msg);
              }
            }
        ,"json");
      }
    });
      
    $("#stpartdate,#etpartdate").datepicker({ picker: "<button class='calpick'></button>"});    
    var cv =$("#colorvalue").val() ;
    if(cv=="") {
      cv="-1";
    }
    $("#calendarcolor").colorselect({ title: "Color", index: cv, hiddenid: "colorvalue" });
    //to define parameters of ajaxform
    var options = {
      beforeSubmit: function() {
        return true;
      },
      dataType: "json",
      success: function(data) {
        alert(data.Msg);
        if (data.IsSuccess) {
          CloseModelWindow(null,true);  
        }
      }
    };
    $.validator.addMethod("date", function(value, element) {                             
      var arrs = value.split(i18n.datepicker.dateformat.separator);
      var year = arrs[i18n.datepicker.dateformat.year_index];
      var month = arrs[i18n.datepicker.dateformat.month_index];
      var day = arrs[i18n.datepicker.dateformat.day_index];
      var standvalue = [year,month,day].join("-");
      return this.optional(element) || /^(?:(?:1[6-9]|[2-9]\d)?\d{2}[\/\-\.](?:0?[1,3-9]|1[0-2])[\/\-\.](?:29|30))(?: (?:0?\d|1\d|2[0-3])\:(?:0?\d|[1-5]\d)\:(?:0?\d|[1-5]\d)(?: \d{1,3})?)?$|^(?:(?:1[6-9]|[2-9]\d)?\d{2}[\/\-\.](?:0?[1,3,5,7,8]|1[02])[\/\-\.]31)(?: (?:0?\d|1\d|2[0-3])\:(?:0?\d|[1-5]\d)\:(?:0?\d|[1-5]\d)(?: \d{1,3})?)?$|^(?:(?:1[6-9]|[2-9]\d)?(?:0[48]|[2468][048]|[13579][26])[\/\-\.]0?2[\/\-\.]29)(?: (?:0?\d|1\d|2[0-3])\:(?:0?\d|[1-5]\d)\:(?:0?\d|[1-5]\d)(?: \d{1,3})?)?$|^(?:(?:16|[2468][048]|[3579][26])00[\/\-\.]0?2[\/\-\.]29)(?: (?:0?\d|1\d|2[0-3])\:(?:0?\d|[1-5]\d)\:(?:0?\d|[1-5]\d)(?: \d{1,3})?)?$|^(?:(?:1[6-9]|[2-9]\d)?\d{2}[\/\-\.](?:0?[1-9]|1[0-2])[\/\-\.](?:0?[1-9]|1\d|2[0-8]))(?: (?:0?\d|1\d|2[0-3])\:(?:0?\d|[1-5]\d)\:(?:0?\d|[1-5]\d)(?:\d{1,3})?)?$/.test(standvalue);
    }, "Invalid date format");
    $.validator.addMethod("time", function(value, element) {
      return this.optional(element) || /^([0-1]?[0-9]|2[0-3]):([0-5][0-9])$/.test(value);
    }, "Invalid time format");
    $.validator.addMethod("safe", function(value, element) {
      return this.optional(element) || /^[^$\<\>]+$/.test(value);
    }, "$<> not allowed");
    $("#fmEdit").validate({
      submitHandler: function(form) { $("#fmEdit").ajaxSubmit(options); },
      errorElement: "div",
      errorClass: "cusErrorPanel",
      errorPlacement: function(error, element) {
        showerror(error, element);
      }
    });
    function showerror(error, target) {
      var pos = target.position();
      var height = target.height();
      var newpos = { left: pos.left, top: pos.top + height + 2 }
      var form = $("#fmEdit");             
      error.appendTo(form).css(newpos);
    }
  });
  
  // Patient Search Dailog
  function getPatientSearch() {
		$('#dlgPatientSearch').dialog('open');
	}
  
  // Patient Search
  function doSearch(){
    $('#dgPatients').edatagrid('load',{  
      option: $("input[name=searchoption]").val(),
      keyword: $('#searchword').val(),
    }); 
  }
  
  $(function(){
    // Category Change and Load Title
    $('#category').combobox({
      onSelect: function(param){
        //var val = $('#category').combobox('getValue');
        $('#title').val(param.label);
      },
    });
    
    // Search and Load Patient Data to Grid
		$('#dgPatients').edatagrid({ 
      onSelect:function(rowIndex, rowData){
        $('#patient').val(rowData['name']);
        $('#patient_id').val(rowData['id']);
        $('#dlgPatientSearch').dialog('close');
      },
    }); 
  });
</script>      
<style>     
  .calpick     {        
    width:16px;   
    height:16px;     
    border:none;        
    cursor:pointer;        
    background:url("sample-css/cal.gif") no-repeat center 2px;        
    margin-left:-22px;    
  }      
</style>

<div class="easyui-tabs" data-options="tools:'#tab-tools'" style="width:785px;height:365px;">
  <!-- Start Patient Tab -->
  <div title="Patient" style="padding:10px">
    <div>
      <!--
      <div class="toolBotton" style="width:20px">           
        <a id="Savebtn" class="imgbtn" href="javascript:void(0);">                
          <span class="Save"  title="Save the calendar">Save(<u>S</u>)
          </span>          
        </a>                           
        <?php if(isset($event)){ ?>
          <a id="Deletebtn" class="imgbtn" href="javascript:void(0);">                    
            <span class="Delete" title="Cancel the calendar">Delete(<u>D</u>)
            </span>                
          </a>             
        <?php } ?>            
        <a id="Closebtn1" class="imgbtn" href="javascript:void(0);">                
          <span class="Close" title="Close the window" >Close
          </span></a>            
        </a>        
      </div>
      -->
      <div style="clear: both"> </div>        
      <div class="infocontainer"
           style="width:98%;height:auto;background:#fafafa;padding:5px;margin-top:5px;margin-bottom:15px;
           border:1px solid #95B8E7; box-shadow: 10px 10px 5px #E0E0EB;">            
        <form action="./dataFeed?method=adddetails<?php //echo isset($event)?"&id=".$event->Id:""; ?>" class="fform" id="fmEdit" method="post">                 
          <table  width='100%' border='0'>
            <tr>
              <td width='50%'>
                <table width='100%' style="height:275px;padding:10px;border:1px solid #95B8E7;">
                  <tr>
                    <td><?php echo xlt('Color Picker'); ?></td>
                    <td colspan='3'><div id="calendarcolor" style="width:50px"></div></td>
                  </tr>
                  <tr>
                    <td><?php echo xlt('Category'); ?></td>
                    <td>
                      <input id='category' name='category' class="easyui-combobox" data-options="
																editable:false, 
																valueField: 'value',
																textField: 'label',
																url:'./getCategories?opt=addeditpatient'" />
                    </td>
                  </tr>
                  <tr>
                    <td><?php echo xlt('Title'); ?></td>
                    <td><input type='text' id='title' name='title' value='' /></td>
                  </tr>
                  <tr>
                    <td><?php echo xlt('Facility'); ?></td>
                    <td colspan='3'>
                      <input name='facility' class="easyui-combobox" data-options="
                                      editable:false, 
                                      valueField: 'value',
                                      textField: 'label',
                                      url:'./getFacilities?opt=addedit'" />
                    </td>
                  </tr>
                  <tr>
                    <td><?php echo xlt('Billing Facility'); ?></td>
                    <td colspan='3'>
                      <input name='billing_facility' class="easyui-combobox" data-options="
                                      editable:false, 
                                      valueField: 'value',
                                      textField: 'label',
                                      url:'./getBillingFacility'" />
                    </td>
                  </tr>
                  <tr>
                    <td><?php echo xlt('Patient'); ?></td>
                    <td>
                      <input type='text' id='patient' name='patient' value='' readonly onclick="getPatientSearch();" />
                      <input type='hidden' id='patient_id' name='patient_id' value='' />
                    </td>
                    <td colspan='2'>&nbsp;</td>
                  </tr>
                  <tr>
                    <td><?php echo xlt('Provider'); ?></td>
                    <td>
                      <input name='provider' class="easyui-combobox" data-options="
                                      editable:false,
                                      valueField: 'value',
                                      textField: 'label',
                                      url:'./getProviders?opt=addedit'" />
                    </td>
                  </tr>
                  <tr>
                    <td><?php echo xlt('Status'); ?></td>
                    <td>
                      <input name='status' class="easyui-combobox"  data-options="
                                      editable:false,
                                      valueField: 'value',
                                      textField: 'label',
                                      url:'./getStatus'" />
                    </td>
                    
                  </tr>
                  <tr>
                    <td><?php echo xlt('Comments'); ?></td>
                    <td>
                      <textarea name="comments" rows='5' cols='10'
                                                      class="easyui-validatebox combo validatebox-text"
                                                      style="height:40px; width:68%" ></textarea>
                    </td>
                    <td colspan='2'></td>
                  </tr>
                </table>
              </td>
              <td valign='top'>
                <table width='100%'>
                  <tr>
                    <td>
                      <table width='100%' border='0' style="height:134px;padding:10px;border:1px solid #95B8E7;">
                        <tr>
                          <td colspan='4'>
                            <input id="IsAllDayEvent" name="IsAllDayEvent"
                                   type="checkbox" value="1" <?php if(isset($event)&&$event->IsAllDayEvent!=0) {echo "checked";} ?>/> <?php echo xlt('All day event'); ?>
                          </td>
                        </tr>
                        <tr>
                          <td width='20%' style="padding-left:5px"><?php echo xlt('Date'); ?></td>
                          <td width='20%'>
                           <input MaxLength="10" class="required date"
                                 id="stpartdate" name="stpartdate" style="padding-left:2px;width:90px;"
                                 type="text" value="<?php echo isset($event)?$sarr[0]:""; ?>" />
                          </td>
                          <td width='10%'><?php echo xlt('Time'); ?></td>
                          <td>
                            <input MaxLength="5" class="required time"
                                   id="stparttime" name="stparttime" style="width:40px;"
                                   type="text" value="<?php echo isset($event)?$sarr[1]:""; ?>" />
                          </td>                      
                        </tr>
                        <tr>
                          <td style="padding-left:5px"><?php echo xlt('Duration'); ?></td>
                          <td><input type='text' id='title' name='title' size='3' value='' /> &nbsp; <?php echo xlt('Minutes'); ?></td>
                          <td>&nbsp;</td><td>&nbsp;</td>
                        </tr>
                      </table>
                    </td>
                  </tr>
                  <tr>
                    <td>
                    </td>
                  </tr>
                  <tr>
                    <td>
                      <table width='100%' border='0' style="height:134px;padding:10px;border:1px solid #95B8E7;">
                        <tr>
                          <td colspan='2' width='30%'>
                            <input id="repeats" name="repeats"
                                type="checkbox" value="1" <?php if(isset($event)&&$event->repeats!=0) {echo "checked";} ?>/>
                                  <?php echo xlt('Repeats'); ?>
                          </td>
                        </tr>
                        <tr>
                          <td>&nbsp;</td>
                          <td colspan='2'>
                            <span style="padding-right:10px;">
                              <input class="easyui-combobox" style="width:60px" data-options="
                                                  valueField: 'value',
                                                  textField: 'label',
                                                  editable:false,
                                                  data: [{
                                                    label: 'Every',
                                                    value: '1',
                                                    selected:true,
                                                  },{
                                                    label: '2nd',
                                                    value: '2'
                                                  },{
                                                    label: '3rd',
                                                    value: '3'
                                                  },{
                                                    label: '4th',
                                                    value: '4'
                                                  },{
                                                    label: '5th',
                                                    value: '5'
                                                  },{
                                                    label: '6th',
                                                    value: '6'
                                                  },]" />
                            
                            </span>
                            <span>
                              <input class="easyui-combobox" style="width:60px" data-options="
                                                  valueField: 'value',
                                                  textField: 'label',
                                                  editable:false,
                                                  data: [{
                                                    label: 'Day',
                                                    value: '0',
                                                    selected:true,
                                                  },{
                                                    label: 'Workday',
                                                    value: '1'
                                                  },{
                                                    label: 'Week',
                                                    value: '2'
                                                  },{
                                                    label: 'Month',
                                                    value: '3'
                                                  },{
                                                    label: 'Year',
                                                    value: '4'
                                                  },{
                                                    label: '?',
                                                    value: '5'
                                                  },{
                                                    label: '?',
                                                    value: '6'
                                                  },]" />
                            
                          </td>
                        </tr>
                        <tr>
                          <td style="padding-left:5px"><?php echo xlt('Until'); ?></td>
                          <td><input id="dtUntil" type="text" class="easyui-datebox" data-options="editable:false"></td>
                        </tr>
                      </table>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
            <!--
            <tr>
              <td><?php echo xlt('Color Picker'); ?></td>
              <td colspan='3'><div id="calendarcolor" style="width:50px"></div></td>
            </tr>
            <tr>
              <td><?php echo xlt('Category'); ?></td>
              <td>
                <input class="easyui-combobox" data-options="
																editable:false, 
																valueField: 'value',
																textField: 'label',
																url:'./getCategories?opt=addedit'" />
              </td>
              <td colspan='2'>
                <input id="IsAllDayEvent" name="IsAllDayEvent"
                       type="checkbox" value="1" <?php if(isset($event)&&$event->IsAllDayEvent!=0) {echo "checked";} ?>/> <?php echo xlt('All day event'); ?>
              </td>

            </tr>
            <tr>
              <td><?php echo xlt('Date'); ?></td>
              <td>--><!--<input id="dtFrom" type="text" class="easyui-datebox" data-options="editable:false"></input>-->
               <!-- <input MaxLength="10" class="required date"
                     id="stpartdate" name="stpartdate" style="padding-left:2px;width:90px;"
                     type="text" value="<?php echo isset($event)?$sarr[0]:""; ?>" />
              </td>
              <td><?php echo xlt('Time'); ?></td>
              <td>
                <input MaxLength="5" class="required time"
                       id="stparttime" name="stparttime" style="width:40px;"
                       type="text" value="<?php echo isset($event)?$sarr[1]:""; ?>" />
              </td>                      
                                     
            </tr>
            <tr>
              <td><?php echo xlt('Title'); ?></td>
              <td><input type='text' id='title' name='title' value='' /></td>
              <td><?php echo xlt('Duration'); ?></td>
              <td><input type='text' id='title' name='title' size='6' value='' /> &nbsp; <?php echo xlt('Minutes'); ?></td>
            </tr>
            <tr>
              <td><?php echo xlt('Facility'); ?></td>
              <td colspan='3'>
                <input class="easyui-combobox" data-options="
																editable:false, 
																valueField: 'value',
																textField: 'label',
																url:'./getFacilities?opt=addedit'" />
              </td>
            </tr>
            <tr>
              <td><?php echo xlt('Billing Facility'); ?></td>
              <td colspan='3'>
                <input class="easyui-combobox" data-options="
																editable:false, 
																valueField: 'value',
																textField: 'label',
																url:'./getBillingFacility'" />
              </td>
            </tr>
            
            <tr>
              <td><?php echo xlt('Patient'); ?></td>
              <td><input type='text' id='patient' name='patient' value='' readonly onclick="alert('search patient');" /></td>
              <td colspan='2'>&nbsp;</td>
            </tr>
            <tr>
              <td><?php echo xlt('Provider'); ?></td>
              <td>
                <input class="easyui-combobox" data-options="
																editable:false,
																valueField: 'value',
																textField: 'label',
																url:'./getProviders?opt=addedit'" />
              </td>
              <td><input id="repeats" name="repeats"
                       type="checkbox" value="1" <?php if(isset($event)&&$event->repeats!=0) {echo "checked";} ?>/><?php echo xlt('Repeats'); ?></td>
              
              <td>
                <span style="padding-right:5px">
                  <input class="easyui-combobox" style="width:60px" data-options="
                                      valueField: 'value',
                                      textField: 'label',
                                      editable:false,
                                      data: [{
                                        label: 'Every',
                                        value: '1',
                                        selected:true,
                                      },{
                                        label: '2nd',
                                        value: '2'
                                      },{
                                        label: '3rd',
                                        value: '3'
                                      },{
                                        label: '4th',
                                        value: '4'
                                      },{
                                        label: '5th',
                                        value: '5'
                                      },{
                                        label: '6th',
                                        value: '6'
                                      },]" />
                
                
                  <input class="easyui-combobox" style="width:60px" data-options="
                                      valueField: 'value',
                                      textField: 'label',
                                      editable:false,
                                      data: [{
                                        label: 'Day',
                                        value: '0',
                                        selected:true,
                                      },{
                                        label: 'Workday',
                                        value: '1'
                                      },{
                                        label: 'Week',
                                        value: '2'
                                      },{
                                        label: 'Month',
                                        value: '3'
                                      },{
                                        label: 'Year',
                                        value: '4'
                                      },{
                                        label: '?',
                                        value: '5'
                                      },{
                                        label: '?',
                                        value: '6'
                                      },]" />
                </span>
              </td>
            </tr>
            <tr>
              <td><?php echo xlt('Status'); ?></td>
              <td>
                <input class="easyui-combobox" data-options="
																editable:false,
																valueField: 'value',
																textField: 'label',
																url:'./getStatus'" />
              </td>
              <td><?php echo xlt('Until'); ?></td>
              <td><input id="dtUntil" type="text" class="easyui-datebox" data-options="editable:false"></td>
            </tr>
            <tr>
              <td><?php echo xlt('Comments'); ?></td>
              <td>
                <textarea name="comments" rows='5' cols='10'
                                                class="easyui-validatebox combo validatebox-text"
                                                style="height:40px; width:60%" ></textarea>
              </td>
              <td colspan='2'></td>
            </tr>
            -->
          </table>
          
        
          <!--
          <label>                    
            <span>*Subject:</span>                    
              <div id="calendarcolor"></div>
              <input MaxLength="200" class="required safe" id="Subject" name="Subject" style="width:85%;" type="text" value="<?php echo isset($event)?$event->Subject:"" ?>" />                     
              <input id="colorvalue" name="colorvalue" type="hidden" value="<?php echo isset($event)?$event->Color:"" ?>" />                
          </label>                 
          <label>                    
            <span>*Time:</span>                    
            <div>  
              <?php if(isset($event)){
                $sarr = explode(" ", php2JsTime(mySql2PhpTime($event->StartTime)));
                $earr = explode(" ", php2JsTime(mySql2PhpTime($event->EndTime)));
              }?>                    
              <input MaxLength="10" class="required date" id="stpartdate" name="stpartdate" style="padding-left:2px;width:90px;" type="text" value="<?php echo isset($event)?$sarr[0]:""; ?>" />                       
              <input MaxLength="5" class="required time" id="stparttime" name="stparttime" style="width:40px;" type="text" value="<?php echo isset($event)?$sarr[1]:""; ?>" />To                       
              <input MaxLength="10" class="required date" id="etpartdate" name="etpartdate" style="padding-left:2px;width:90px;" type="text" value="<?php echo isset($event)?$earr[0]:""; ?>" />                       
              <input MaxLength="50" class="required time" id="etparttime" name="etparttime" style="width:40px;" type="text" value="<?php echo isset($event)?$earr[1]:""; ?>" />                                            
              <label class="checkp"> 
                <input id="IsAllDayEvent" name="IsAllDayEvent" type="checkbox" value="1" <?php if(isset($event)&&$event->IsAllDayEvent!=0) {echo "checked";} ?>/>          All Day Event                      
              </label>                    
            </div>                
          </label>                 
          <label>                    
            <span>Location:</span>                    
            <input MaxLength="200" id="Location" name="Location" style="width:95%;" type="text" value="<?php echo isset($event)?$event->Location:""; ?>" />                 
          </label>                 
          <label>                    
            <span>Remark:</span>                    
            <textarea cols="20" id="Description" name="Description" rows="2" style="width:95%; height:70px">
              <?php echo isset($event)?$event->Description:""; ?>
            </textarea>                
          </label>                
            <input id="timezone" name="timezone" type="hidden" value="" />
           -->
          </form>         
        </div>         
      </div>
    </div>
    <!-- End Patient Tab -->
    <!-- Start Provider Tab -->
    <div title="Provider" data-options="closable:true" style="padding:10px">  
      <div class="infocontainer"
           style="width:98%;height:auto;background:#fafafa;padding:5px;margin-top:5px;margin-bottom:15px;
           border:1px solid #95B8E7; box-shadow: 10px 10px 5px #E0E0EB;">
        <form>
          <table  width='100%' border='0'>
              <tr>
                <td width='50%'>
                  <table width='100%' style="height:275px;padding:10px;border:1px solid #95B8E7;">
                    <tr>
                      <td><?php echo xlt('Color Picker'); ?></td>
                      <td colspan='3'><div id="calendarcolor" style="width:50px"></div></td>
                    </tr>
                    <tr>
                      <td><?php echo xlt('Category'); ?></td>
                      <td>
                        <input class="easyui-combobox" data-options="
                                  editable:false, 
                                  valueField: 'value',
                                  textField: 'label',
                                  url:'./getCategories?opt=addeditprovider'" />
                      </td>
                    </tr>
                    <tr>
                      <td><?php echo xlt('Title'); ?></td>
                      <td><input type='text' id='title' name='title' value='' /></td>
                    </tr>
                    <tr>
                      <td><?php echo xlt('Facility'); ?></td>
                      <td colspan='3'>
                        <input class="easyui-combobox" data-options="
                                        editable:false, 
                                        valueField: 'value',
                                        textField: 'label',
                                        url:'./getFacilities?opt=addedit'" />
                      </td>
                    </tr>
                    <tr>
                      <td><?php echo xlt('Billing Facility'); ?></td>
                      <td colspan='3'>
                        <input class="easyui-combobox" data-options="
                                        editable:false, 
                                        valueField: 'value',
                                        textField: 'label',
                                        url:'./getBillingFacility'" />
                      </td>
                    </tr>

                    <tr>
                      <td><?php echo xlt('Provider'); ?></td>
                      <td>
                        <input class="easyui-combobox" data-options="
                                        editable:false,
                                        valueField: 'value',
                                        textField: 'label',
                                        url:'./getProviders?opt=addedit'" />
                      </td>
                    </tr>
                    <tr>
                      <td><?php echo xlt('Pref Cat'); ?></td>
                      <td>
                        <input class="easyui-combobox"  data-options="
                                        editable:false,
                                        valueField: 'value',
                                        textField: 'label',
                                        url:'./getCategories?opt=addeditproviderprefcat'" />
                      </td>
                      
                    </tr>
                    <tr>
                      <td><?php echo xlt('Comments'); ?></td>
                      <td>
                        <textarea name="comments" rows='5' cols='10'
                                                        class="easyui-validatebox combo validatebox-text"
                                                        style="height:40px; width:68%" ></textarea>
                      </td>
                      <td colspan='2'></td>
                    </tr>
                  </table>
                </td>
                <td valign='top'>
                  <table width='100%'>
                    <tr>
                      <td>
                        <table width='100%' border='0' style="height:134px;padding:10px;border:1px solid #95B8E7;">
                          <tr>
                            <td colspan='4'>
                              <input id="IsAllDayEvent" name="IsAllDayEvent"
                                     type="checkbox" value="1" <?php if(isset($event)&&$event->IsAllDayEvent!=0) {echo "checked";} ?>/> <?php echo xlt('All day event'); ?>
                            </td>
                          </tr>
                          <tr>
                            <td width='20%' style="padding-left:5px"><?php echo xlt('Date'); ?></td>
                            <td width='20%'>
                             <input MaxLength="10" class="required date"
                                   id="stpartdate" name="stpartdate" style="padding-left:2px;width:90px;"
                                   type="text" value="<?php echo isset($event)?$sarr[0]:""; ?>" />
                            </td>
                            <td width='10%'><?php echo xlt('Time'); ?></td>
                            <td>
                              <input MaxLength="5" class="required time"
                                     id="etparttime" name="etparttime" style="width:40px;"
                                     type="text" value="<?php echo isset($event)?$sarr[1]:""; ?>" />
                            </td>                      
                          </tr>
                          <tr>
                            <td width='20%' style="padding-left:5px"><?php echo xlt('Duration'); ?></td>
                            <td><input type='text' id='title' name='title' size='3' value='' /> &nbsp; <?php echo xlt('Minutes'); ?></td>
                            <td>&nbsp;</td><td>&nbsp;</td>
                          </tr>
                        </table>
                      </td>
                    </tr>
                    <tr>
                      <td>
                      </td>
                    </tr>
                    <tr>
                      <td>
                        <table width='100%' border='0' style="height:134px;padding:10px;border:1px solid #95B8E7;">
                          <tr>
                            <td colspan='2' width='30%'>
                              <input id="repeats" name="repeats"
                                  type="checkbox" value="1" <?php if(isset($event)&&$event->repeats!=0) {echo "checked";} ?>/>
                                    <?php echo xlt('Repeats'); ?>
                            </td>
                          </tr>
                          <tr>
                            <td>&nbsp;</td>
                            <td colspan='2'>
                              <span style="padding-right:10px;">
                                <input class="easyui-combobox" style="width:60px" data-options="
                                                    valueField: 'value',
                                                    textField: 'label',
                                                    editable:false,
                                                    data: [{
                                                      label: 'Every',
                                                      value: '1',
                                                      selected:true,
                                                    },{
                                                      label: '2nd',
                                                      value: '2'
                                                    },{
                                                      label: '3rd',
                                                      value: '3'
                                                    },{
                                                      label: '4th',
                                                      value: '4'
                                                    },{
                                                      label: '5th',
                                                      value: '5'
                                                    },{
                                                      label: '6th',
                                                      value: '6'
                                                    },]" />
                              
                              </span>
                              <span>
                                <input class="easyui-combobox" style="width:60px" data-options="
                                                    valueField: 'value',
                                                    textField: 'label',
                                                    editable:false,
                                                    data: [{
                                                      label: 'Day',
                                                      value: '0',
                                                      selected:true,
                                                    },{
                                                      label: 'Workday',
                                                      value: '1'
                                                    },{
                                                      label: 'Week',
                                                      value: '2'
                                                    },{
                                                      label: 'Month',
                                                      value: '3'
                                                    },{
                                                      label: 'Year',
                                                      value: '4'
                                                    },{
                                                      label: '?',
                                                      value: '5'
                                                    },{
                                                      label: '?',
                                                      value: '6'
                                                    },]" />
                              
                            </td>
                          </tr>
                          <tr>
                            <td style="padding-left:5px;"><?php echo xlt('Until'); ?></td>
                            <td><input id="dtUntil" type="text" class="easyui-datebox" data-options="editable:false"></td>
                          </tr>
                        </table>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>
          </table>
        </form>
      </div>
    </div>
    <!-- End Provider Tab -->
</div>
<div id="tab-tools">  
      <a id="Savebtn"       href="javascript:void(0)" class="easyui-linkbutton" data-options="plain:true,iconCls:'icon-save'"><?php echo xlt('Save'); ?></a>  
      <a id="findbtn"       href="javascript:void(0)" class="easyui-linkbutton" data-options="plain:true,iconCls:'icon-search'" onclick="alert('find');"><?php echo xlt('Find Avilable'); ?></a>
      <a id="Deletebtn"     href="javascript:void(0)" class="easyui-linkbutton" data-options="plain:true,iconCls:'icon-delete'" onclick="alert('delete');"><?php echo xlt('Delete'); ?></a>
      <a id="Closebtn"      href="javascript:void(0)" class="easyui-linkbutton" data-options="plain:true,iconCls:'icon-close'"><?php echo xlt('Cancel'); ?></a>
      <a id="duplicatebtn"  href="javascript:void(0)" class="easyui-linkbutton" data-options="plain:true,iconCls:'icon-duplicate'" onclick="alert('duplicate');"><?php echo xlt('Create Duplicate'); ?></a> 
</div> 

<!-- Start Patient Search-->
<div id="dlgPatientSearch" class="easyui-dialog" title="Patient Search" data-options="iconCls:'icon-search'"
     style="width:750px;height:350px;padding:10px 20px" closed="true">
    <div class="ftitle" id='dlgtitle' style="color:#0068A4"><?php echo xlt('Patient Search'); ?></div>
    <div style="width:100%;background:#fafafa;padding:1px;margin-top:5px;margin-bottom:15px;border:1px solid #95B8E7;">
      <table>
        <tr>
          <td>Search By</td>
          <td>
            <input id='searchoption' name='searchoption' class="easyui-combobox" style="width:60px" data-options="
                                                    valueField: 'value',
                                                    textField: 'label',
                                                    editable:false,
                                                    data: [{
                                                      label: 'Name',
                                                      value: 'Name',
                                                      selected:true,
                                                    },{
                                                      label: 'Phone',
                                                      value: 'Phone'
                                                    },{
                                                      label: 'ID',
                                                      value: 'ID'
                                                    },{
                                                      label: 'SSN',
                                                      value: 'SSN'
                                                    },{
                                                      label: 'DOB',
                                                      value: 'DOB'
                                                    },]" />
          </td>
          <td>For</td>
          <td><input type='text' id='searchword' name='searchword' value='' /></td>
          <td>
            <a id="patientsearch"  href="javascript:void(0)"
               class="easyui-linkbutton" data-options="plain:true,iconCls:'icon-search'"
               onclick="doSearch();"><?php echo xlt('Search'); ?></a>
          </td>
        </tr>
      </table>
    </div>
    <table  id="dgPatients" title="Patients" class="easyui-datagrid" style="width:700px;height:200px"  
            url="./getPatients"
            idField="id" 
            rownumbers="true" fitColumns="true" singleSelect="true">  
        <thead>  
            <tr> 
                <th field="name" width="50"><?php echo xlt('Name'); ?></th>	
                <th field="phone_home" width="50"><?php echo xlt('Phone'); ?></th>  
                <th field="ss" width="50"><?php echo xlt('SS'); ?></th>  
                <th field="DOB" width="50"><?php echo xlt('DOB'); ?></th>
                <th field="id" width="50"><?php echo xlt('ID'); ?></th> 
            </tr>  
        </thead>  
    </table>
</div>
<!-- End Patient Search -->
<script>
  $(document).ready(function() {  
    $("footer").hide();
    $("hr").hide();
    $('body').css('overflow','hidden');
  });
</script>