<?php 
		// module/Calendar/view/calendar/calendar/index.phtml:
		//echo '<pre>'; print_r($this->result);echo '</pre>';
		$arrProvider = array();
		$arrProvider = explode(',' , $this->provider);
		
		//echo 'test'.$this->$provider;
		echo '<pre>'; print_r($this->provider);echo '</pre>';
		//if (in_array($value['id'], $arrProviderID)) {
				
		//}
		$arr = array();
		for ($i = 0; $i < count($this->result); $i++) {
        $arr[$i]['id'] 		= $result[$i]['id'];
				$arr[$i]['lname'] = $result[$i]['lname'];
				$arr[$i]['fname'] = $result[$i]['fname'];
		}

		
		//echo $this->headScript()->prependFile($this->basePath() . '/js/calendar/calendar.js.php');

		//require_once($GLOBALS['include_root'] . "/modules/zend_modules/public/js/calendar/calendar.js.php");
		
?>

<script>
		$(document).ready(function() {     
				<?php
					$i = 1;
					foreach ($arr as $key => $value) {
				?>
				var view="day";
				var  opt = '';
				opt = "&providerID=" + <?php echo $value['id']; ?>;
				var DATA_FEED_URL = "./dataFeed";
				var op = {
						view: view,
						theme:3,
						showday: new Date(),
						EditCmdhandler:Edit,
						DeleteCmdhandler:Delete,
						ViewCmdhandler:View,    
						onWeekOrMonthToDay:wtd,
						onBeforeRequestData: cal_beforerequest,
						onAfterRequestData: cal_afterrequest,
						onRequestDataError: cal_onerror, 
						autoload:true,
						url: DATA_FEED_URL + "?method=list" + opt,  
						quickAddUrl: DATA_FEED_URL + "?method=add", 
						quickUpdateUrl: DATA_FEED_URL + "?method=update",
						quickDeleteUrl: DATA_FEED_URL + "?method=remove",
						intervalTime: 7.5,
				};
				var $dv = $("#calhead");
				var _MH = document.documentElement.clientHeight;
				var dvH = $dv.height() + 2;
				op.height = _MH - dvH;
				op.eventItems =[];
		
				var p = $("#gridcontainer<?php echo $i; ?>").bcalendar(op).BcalGetOp();
				if (p && p.datestrshow) {
						$("#txtdatetimeshow").text(p.datestrshow);
				}
				
				$("#caltoolbar").noSelect();

				$("#hdtxtshow").datepicker({ picker: "#txtdatetimeshow", showtarget: $("#txtdatetimeshow"),
				onReturn:function(r){                       
								var p = $("#gridcontainer<?php echo $i; ?>").gotoDate(r).BcalGetOp();
								if (p && p.datestrshow) {
										$("#txtdatetimeshow").text(p.datestrshow);
								}
						} 
				});
				
				function cal_beforerequest(type)
				{
						var t="Loading data...";
						switch(type)
						{
								case 1:
										t="Loading data...";
										break;
								case 2:                      
								case 3:  
								case 4:    
										t="The request is being processed ...";                                   
										break;
						}
						$("#errorpannel").hide();
						$("#loadingpannel").html(t).show();    
				}
				
				function cal_afterrequest(type)
				{
						switch(type)
						{
								case 1:
										$("#loadingpannel").hide();
										break;
								case 2:
								case 3:
								case 4:
										$("#loadingpannel").html("Success!");
										window.setTimeout(function(){ $("#loadingpannel").hide();},2000);
								break;
						}              
					 
				}
				
				function cal_onerror(type,data)
				{
						$("#errorpannel").show();
				}
				
				function Edit(data)
				{
					 var eurl="edit.php?id={0}&start={2}&end={3}&isallday={4}&title={1}";   
						if(data)
						{
								var url = StrFormat(eurl,data);
								OpenModelWindow(url,{ width: 600, height: 400, caption:"Manage  The Calendar",onclose:function(){
									 $("#gridcontainer<?php echo $i; ?>").reload();
								}});
						}
				}
				
				function View(data)
				{
						var str = "";
						$.each(data, function(i, item){
								str += "[" + i + "]: " + item + "\n";
						});
						alert(str);               
				}
				
				function Delete(data,callback)
				{           
						$.alerts.okButton="Ok";  
						$.alerts.cancelButton="Cancel";  
						hiConfirm("Are You Sure to Delete this Event", 'Confirm',function(r){ r && callback(0);});           
				}
				
				function wtd(p)
				{
					 if (p && p.datestrshow) {
								$("#txtdatetimeshow").text(p.datestrshow);
						}
						$("#caltoolbar div.fcurrent").each(function() {
								$(this).removeClass("fcurrent");
						})
						$("#showdaybtn").addClass("fcurrent");
				}
				
				//to show day view
				$("#showdaybtn").click(function(e) {
						//document.location.href="#day";
						$("#caltoolbar div.fcurrent").each(function() {
								$(this).removeClass("fcurrent");
						})
						$(this).addClass("fcurrent");
						var p = $("#gridcontainer<?php echo $i; ?>").swtichView("day").BcalGetOp();
						if (p && p.datestrshow) {
								$("#txtdatetimeshow").text(p.datestrshow);
						}
				});
				
				//to show week view
				$("#showweekbtn").click(function(e) {
						window.location.assign("./calendarMonthWeek?view=week");
						//document.location.href="#week";
						$("#caltoolbar div.fcurrent").each(function() {
								$(this).removeClass("fcurrent");
						})
						$(this).addClass("fcurrent");
						var p = $("#gridcontainer<?php echo $i; ?>").swtichView("week").BcalGetOp();
						if (p && p.datestrshow) {
								$("#txtdatetimeshow").text(p.datestrshow);
						}
				});
				
				//to show month view
				$("#showmonthbtn").click(function(e) {
						window.location.assign("./calendarMonthWeek?view=month");
						//document.location.href="#month";
						$("#caltoolbar div.fcurrent").each(function() {
								$(this).removeClass("fcurrent");
						})
						$(this).addClass("fcurrent");
						var p = $("#gridcontainer<?php echo $i; ?>").swtichView("month").BcalGetOp();
						if (p && p.datestrshow) {
								$("#txtdatetimeshow").text(p.datestrshow);
						}
				});
				
				$("#showreflashbtn").click(function(e){
						$("#gridcontainer<?php echo $i; ?>").reload();
				});

				//Add a new event
				$("#faddbtn").click(function(e) {
						var url ="edit.php";
						OpenModelWindow(url,{ width: 500, height: 400, caption: "Create New Calendar"});
				});
				
				//go to today
				$("#showtodaybtn").click(function(e) {
						var p = $("#gridcontainer<?php echo $i; ?>").gotoDate().BcalGetOp();
						if (p && p.datestrshow) {
								$("#txtdatetimeshow").text(p.datestrshow);
						}
				});
				
				//previous date range
				$("#sfprevbtn").click(function(e) {
						var p = $("#gridcontainer<?php echo $i; ?>").previousRange().BcalGetOp();
						if (p && p.datestrshow) {
								$("#txtdatetimeshow").text(p.datestrshow);
						}
				});
				
				//next date range
				$("#sfnextbtn").click(function(e) {
						var p = $("#gridcontainer<?php echo $i; ?>").nextRange().BcalGetOp();
						if (p && p.datestrshow) {
								$("#txtdatetimeshow").text(p.datestrshow);
						}
				});
			<?php $i++; } ?>
		});
		
		$(document).ready(function() {  
				var target = $("#target");
				$("select")
						.multiselect()
						.bind("multiselectclick multiselectcheckall multiselectuncheckall", function( event, ui ){
								var checkedValues = $.map($(this).multiselect("getChecked"), function( input ){
										return input.value;
								});
								target.html(
										checkedValues.length 
												? checkedValues.join(', ')
												: 'Please Select Provider' 
								);
								if (target.text() != 'Please Select Provider') {
									//window.location.assign("./index?providerID=" + target.text());
								}
				})
				.triggerHandler("multiselectclick");
		});
		
	
</script>
<div id="target" style="padding: 5px; border: 1px solid #000; width:200px; float:right; display:none">target</div>
<div>
    <div>
				<form style="margin:20px 0">
						<p>
								<select  multiple="multiple" style="width:370px;">
										<?php for ($i = 0; $i < count($this->result); $i++) { ?>
												<option value="<?php echo $result[$i]['id']; ?>"><?php echo $result[$i]['lname'] . ' ' . $result[$i]['fname']; ?></option>
										<?php } ?>
								</select>
						</p>
				</form>
		</div>
			<div id="calhead" style="padding-left:1px;padding-right:1px;">          
            <div class="cHead"><div class="ftitle">Calendar</div>
            <div id="loadingpannel" class="ptogtitle loadicon" style="display: none;">Loading data...</div>
             <div id="errorpannel" class="ptogtitle loaderror" style="display: none;">Sorry, could not load your data, please try again later</div>
            </div>          
            
            <div id="caltoolbar" class="ctoolbar">
              <div id="faddbtn" class="fbutton">
                <div><span title='Click to Create New Event' class="addcal">

                New Event                
                </span></div>
            </div>
            <div class="btnseparator"></div>
             <div id="showtodaybtn" class="fbutton">
                <div><span title='Click to back to today ' class="showtoday">
                Today</span></div>
            </div>
              <div class="btnseparator"></div>

            <div id="showdaybtn" class="fbutton  fcurrent">
                <div><span title='Day' class="showdayview">Day</span></div>
            </div>
              <div  id="showweekbtn" class="fbutton">
                <div><span title='Week' class="showweekview">Week</span></div>
            </div>
              <div  id="showmonthbtn" class="fbutton">
                <div><span title='Month' class="showmonthview">Month</span></div>

            </div>
            <div class="btnseparator"></div>
              <div  id="showreflashbtn" class="fbutton">
                <div><span title='Refresh view' class="showdayflash">Refresh</span></div>
                </div>
             <div class="btnseparator"></div>
            <div id="sfprevbtn" title="Prev"  class="fbutton">
              <span class="fprev"></span>

            </div>
            <div id="sfnextbtn" title="Next" class="fbutton">
                <span class="fnext"></span>
            </div>
            <div class="fshowdatep fbutton">
								<div>
										<input type="hidden" name="txtshow" id="hdtxtshow" />
										<span id="txtdatetimeshow">Loading</span>
								</div>
            </div>
            <div class="clear"></div>
            </div>
      </div>
      <div style="padding:1px;">

        <div class="t1 chromeColor">&nbsp;</div>
        <div class="t2 chromeColor">&nbsp;</div>
        <table width='98%' border='0'>
						<tr>
								<?php 
								for ($i = 0; $i < count($this->result); $i++) {
									?>
									<td width='50%'>
										<div style="font-weight:bold; color:#2157CC">
											<?php echo $result[$i]['lname'] . ' ' . $result[$i]['fname']; ?>
										</div>
										<div id="dvCalMain<?php echo ($i + 1); ?>" class="calmain printborder" style="float:left;width:100%">
											<div id="gridcontainer<?php echo ($i + 1); ?>" class="gridcontainer" style="overflow-y: visible;" style="float:left;width:100%">
											</div>
										</div>
									</td>
									<?php } ?>
						</tr>
				</table>
        <div class="t2 chromeColor">&nbsp;</div>
        <div class="t1 chromeColor">&nbsp;
        </div>   
				</div>
     
  </div>

<script type="text/javascript">
$("select").multiselect().multiselectfilter();
</script>