<?php 
	// module/Encounter/view/encounter/encounter/index.phtml:

	$form = $this->form;
	$form->setAttribute('action', $this->url('encounter', array('action' => 'index')));
	$form->prepare();
	echo $this->form()->openTag($form);

	if ($this->view == 'N') {?>
        <div  title="<?php echo xlt('Encounter'); ?>" style="overflow:auto;padding:10px;">
            <div id="dlg" class="easyui-dialog"
								 title="<?php echo xlt('Message');?>"
															data-options="iconCls:'icon-ok'"
															style="width:400px;height:200px;padding:10px">
                    <div style="margin: 50px; font-size: 14px;">
												<?php echo xlt('You are not authorized to see this encounter. .. !');?>
										</div>
            </div>
        </div>
	<?php } elseif ($this->view == 'F') { ?>
				<div  title="<?php echo xlt('Encounter'); ?>" style="overflow:auto;padding:10px;">
						<div id="dlg" class="easyui-dialog"
								 title="<?php echo xlt('Message');?>"
															data-options="iconCls:'icon-ok'"
															style="width:400px;height:200px;padding:10px">
										<div style="margin: 50px; font-size: 14px;">
												<?php echo xlt('Please select a patient  .. !');?>
										</div>
						</div>
				</div>
	<?php } else {
?>

 	<table width='100%' style="background:linear-gradient(to bottom, #EFF5FF 0px, #E0ECFF 100%) repeat-x scroll 0 0 transparent;">
 	<tr >
	 	<td style="color: #0E2D5F; font-weight: bold;height: 20px;line-height: 20px;">
	 		<div><?php echo xlt('Encounter');?></div>
	 	</td>
 	<td align='right'>
 		<div>
 			<a href="#" class="easyui-linkbutton" data-options="iconCls:'icon-save'" onclick="save();"><?php echo xlt('Save'); ?></a>
 			<a href="../../../../patient_file/history/encounters.php" class="easyui-linkbutton" iconCls="icon-cancel"><?php echo xlt('Cancel'); ?></a>
 		</div>
 	</td>
 	</tr>
 	</table>
 	
	<table id='tt' border='0' class="dv-table gridtable" style="width:100%;background:#fafafa;padding:0px;margin-top:0px;margin-bottom:15px;border:1px solid #95B8E7; box-shadow: 10px 10px 5px #E0E0EB;">
        <tr>
        <td valign='top' width='30%'>
	        <table style="width:100%;height:185px;padding:10px;border:1px solid #95B8E7;">
	        <tr>
	            <td><?php  echo xlt('Visit Category');?>:</td>
	            <td><?php echo $this->formRow($form->get('visitCategory'));?></td>
	        </tr>
	        <tr>
	            <td><?php  echo xlt('Provider');?>:</td>
	            <td><?php echo $this->formRow($form->get('provider'));?></td>
	        </tr>
	        <tr>
	            <td><?php echo xlt('Facility');?>:</td>
	            <td><?php echo $this->formRow($form->get('facility'));?></td>
	        </tr>
	        <tr>
	        	<td><?php echo xlt('Billing Facility');?>:</td> 
	            <td><?php echo $this->formRow($form->get('billingFacility'));?></td>
	        </tr>
	        <tr>
	           	<td><?php echo xlt('Sensitivity');?>:</td>
	            <td><?php echo $this->formRow($form->get('sensitivity'));?></td>
	        </tr>
	   		<tr>
	            <td><?php echo xlt('Date of Service');?>:</td>
	            <td><?php echo $this->formRow($form->get('dtService'));?></td>
	        </tr>
	        <tr>
	        	<td><?php echo xlt('Onset / hosp. Date');?></td>
	            <td><?php echo $this->formRow($form->get('dtOnset'));?></td>
	        </tr>
	        </table>
        </td>
        <td valign='top' width='40%'>
	        <table border='0' align='left' style="width:100%;height:196px;padding:10px;border:1px solid #95B8E7;">
	        <tr>
	       		<td><?php echo xlt('Consultation Brief Description');?>:</td>
	       		<td>
	       			<?php echo xlt('Issues (Injuries/Medical/Allergy)');?>
	       			<a href="#" class="easyui-linkbutton" data-options="iconCls:'icon-add'" onclick="addIssues();"><?php echo xlt('Add'); ?></a>
	       		</td>
	        </tr>
	        <tr>
	        	<td><?php echo $this->formRow($form->get('description'));?></td>
	        	<td><?php echo $this->formRow($form->get('issues[]'));?></td>
	        </tr>
	        <tr>
	        	<td>&nbsp;</td>
	        	<td style="font-size: 9px;">
	        		<?php xl('To link this encounter/consult to an existing issue, click the '
   						. 'desired issue above to highlight it and then click [Save]. '
   						. 'Hold down [Ctrl] button to select multiple issues.','e'); ?>
   				</td>
	        </tr>
	        
	        </table>
        </td>
        <?php if ($this->mode == 'Edit') { ?>
        <td valign='top' width='30%'>
	        <?php if ($GLOBALS['enable_amc_prompting']) { ?>
		      <table border='0' style="width:100%;height:185px;padding:1px;border:1px solid #95B8E7;">
		        <tr height='10%'>
			        <td>
			        	<script>checkAMC('PER')</script>
			        	<?php echo $this->formRow($form->get('provEduRes'));?>
			        </td>
			        <td><?php echo xl('Provided Education Resource(s)?') ?></td>
		        </tr>
		         <tr height='10%'>
			        <td>
			        	<script>checkAMC('PCS')</script>
			        	<?php echo $this->formRow($form->get('provCliSum'));?>
			        </td>
			        <td><?php echo xl('Provided Clinical Summary?') ?></td>
		        </tr>
		         <tr height='10%'>
			        <td>
			        	<script>checkAMC('TTC')</script>
			        	<?php echo $this->formRow($form->get('transTrandCare'));?>
			        </td>
			        <td>
			        	<?php echo xl('Transition/Transfer of Care?') ?>
			        </td>
		        </tr>
		        <tr>
		        	<td colspan='2' height='10px'>
			        	<table border='0' valign='top'  style="margin-left:2em;">
				        	<tr>
					        	<td>
						        	<script>checkAMC('TTC')</script>
					        		<?php echo $this->formRow($form->get('medReconcPerf'));?>
					        	</td>
					        	<td>
					        		<?php echo xl('Medication Reconciliation Performed?') ?>
					        	</td>
				        	</tr>
			        	</table>
		        	</td>
		        </tr>
		        <tr><td></td></tr>
		       </table>
		   	<?php } ?>
        </td>
        <?php } ?>
        </tr>
   </table>
<?php
	}
    echo $this->form()->closeTag();
?>

	<div id="dlg" class="easyui-dialog" style="width:750px;height:415px;padding:10px 20px"  
            closed="true" buttons="#dlg-buttons">  
        <div class="ftitle" id='titleShow'></div>  
        <!--<form id="fm" method="post" novalidate> --> 
        	 <iframe id="urlWindow" name='urlWindow' src="" style="width:100%; height:100%; border: none;"></iframe> 
        <!--</form>  -->
    </div> 
