<?php
// +-----------------------------------------------------------------------------+ 
// Copyright (C) 2013 Z&H Consultancy Services Private Limited <sam@zhservices.com>
//
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
//
// A copy of the GNU General Public License is included along with this program:
// openemr/interface/login/GnuGPL.html
// For more information write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
// 
// Author:   Jacob T.Paul <jacob@zhservices.com>
//
// +------------------------------------------------------------------------------+
echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
        		->prependStylesheet($this->basePath() . '/css/easyui.css')
                        ->prependStylesheet($this->basePath() . '/css/icon.css')
                        ->prependStylesheet($this->basePath() . '/css/demo.css')
			->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
			->prependStylesheet($this->basePath() . '/css/style.css')
			->prependStylesheet($this->basePath() . '/css/suggestion.css')
			->prependStylesheet($this->basePath() . '/css/bubbletip-IE.css')
			->prependStylesheet($this->basePath() . '/css/bubbletip.css')
			->prependStylesheet($this->basePath() . '/css/bubbles.css')
			->prependStylesheet($this->basePath() . '/css/zendlab.css')
			->prependStylesheet($GLOBALS['css_header']) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
					->prependFile($this->basePath() . '/js/lib/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
					->prependFile($this->basePath() . '/js/lib/bootstrap.min.js')
					->prependFile($this->basePath() . '/js/lab/result.js')
					->prependFile($this->basePath() . '/js/lib/jquery.easyui.overrider.js')
					->prependFile($this->basePath() . '/js/lib/jquery.edatagrid.js')
					->prependFile($this->basePath() . '/js/lib/jquery.easyui.min.js')
					->prependFile($this->basePath() . '/js/lib/jquery-1.8.0.min.js')
					?>
    <?php
		if($current_controller == 'lab' && $current_action == 'order'){
				$procedure_order_active = "menu-active";
		}elseif($current_controller == 'Result' && $current_action == 'index'){
				$pending_review_active = "menu-active";
		}elseif($current_controller == 'Result' && $current_action == 'resultEntry'){
				$result_entry_active = "menu-active";
		}elseif($current_controller == 'Pull' && $current_action == 'index'){
				$pull_compendium_active = "menu-active";
		}elseif($current_controller == 'Configuration' && $current_action == 'index'){
				$procudure_config_active = "menu-active";
		}elseif($current_controller == 'Specimen' && $current_action == 'index'){
				$specimen_collection_active = "menu-active";
		}elseif($current_controller == 'lab' && $current_action == 'orderedit'){
				$procedure_order_edit_active = "menu-active";
		}elseif($current_controller == 'provider' && $current_action == 'index'){
				$procedure_provider_active = "menu-active";
		}
?>
    </head>
    <body  class="body_top">
        <div class="container" style="width:100%">
	    <div style="padding:5px;border:1px solid #ddd">
		<?php
		//if(acl_check("module_lab","procedure_order")){
		?>
		<a href="<?php echo $this->url('lab', array('action'=>'index'));?>/index" class="easyui-linkbutton <?php echo $procedure_order_active; ?>" data-options="plain:true"><?php echo xlt('Procedure Order');?></a>
		<a href="<?php echo $this->url('lab', array('action'=>'orderedit'));?>" class="easyui-linkbutton <?php echo $procedure_order_edit_active; ?>" data-options="plain:true"><?php echo xlt('Procedure Order Edit');?></a>
		<?php
		//}
		//if(acl_check("module_lab","procedure_results")){
		?>
		<a id="btn-edit" href="<?php echo $this->url('result', array('action'=>'index'));?>" class="easyui-linkbutton <?php echo $pending_review_active; ?>" data-options="plain:true"><?php echo xlt('Results');?></a>
		<?php //} ?>
		<a href="<?php echo $this->url('specimen', array('action'=>'index'));?>" class="easyui-linkbutton <?php echo $specimen_collection_active; ?>" data-options="plain:true"><?php echo xlt('Specimen Collection');?></a>
		<a href="<?php echo $this->url('result', array('action'=>'resultEntry'));?>" class="easyui-linkbutton <?php echo $result_entry_active; ?>" data-options="plain:true"><?php echo xlt('Result Entry');?></a>
		<a href="<?php echo $this->url('configuration', array('action'=>'index'));?>" class="easyui-linkbutton <?php echo $procudure_config_active; ?>" data-options="plain:true"><?php echo xlt('Procedure Configuration');?></a>
		<a href="<?php echo $this->url('pull', array('action'=>'index'));?>" class="easyui-linkbutton <?php echo $pull_compendium_active; ?>" data-options="plain:true"><?php echo xlt('Pull Compendium');?></a>
		<a href="<?php echo $this->url('provider', array('action'=>'index'));?>" class="easyui-linkbutton <?php echo $procedure_provider_active; ?>" data-options="plain:true"><?php echo xlt('Procedure Providers');?></a>
	    </div>
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2013<?php echo xlt(' by ZHHealthcare');?>. <?php echo xlt('All rights reserved') ?>.</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
