<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
        		->prependStylesheet($this->basePath() . '/css/easyui.css')
                        ->prependStylesheet($this->basePath() . '/css/icon.css')
                        ->prependStylesheet($this->basePath() . '/css/demo.css')
			->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
			->prependStylesheet($this->basePath() . '/css/style.css')
			->prependStylesheet($this->basePath() . '/css/suggestion.css')
			->prependStylesheet($this->basePath() . '/css/bubbletip-IE.css')
			->prependStylesheet($this->basePath() . '/css/bubbletip.css')
			->prependStylesheet($this->basePath() . '/css/bubbles.css')
			->prependStylesheet($this->basePath() . '/css/zendlab.css')
			->prependStylesheet($GLOBALS['css_header']) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
					->prependFile($this->basePath() . '/js/lib/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
					->prependFile($this->basePath() . '/js/lib/bootstrap.min.js')
					->prependFile($this->basePath() . '/js/lab/result.js')
					->prependFile($this->basePath() . '/js/lib/jquery.easyui.overrider.js')
					->prependFile($this->basePath() . '/js/lib/jquery.edatagrid.js')
					->prependFile($this->basePath() . '/js/lib/jquery.easyui.min.js')
					->prependFile($this->basePath() . '/js/lib/jquery-1.8.0.min.js')
					?>
    			      
    </head>
    <body  class="body_top">
        <div class="container">
	    <div style="padding:5px;border:1px solid #ddd">
		<a href="./index" class="easyui-linkbutton" data-options="plain:true"><?php echo xlt('Procedure Order');?></a>
		<a id="btn-edit" href="./result" class="easyui-linkbutton" data-options="plain:true"><?php echo xlt('Pending Review/ Result');?></a>
		<a href="#" class="easyui-linkbutton" data-options="plain:true"><?php echo xlt('Pull Compendium');?></a>
	    </div>
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2013<?php echo xlt(' by ZHHealthcare');?>. <?php echo xlt('All rights reserved') ?>.</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
