<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
				<script type="text/javascript">
						//var jQuery = jQuery.noConflict();
				</script>

				
        <!-- styles -->
        <?php echo $this->headLink()

						->prependStylesheet($this->basePath() . '/css/calendar/selector/jquery-ui.css')
						->prependStylesheet($this->basePath() . '/css/calendar/selector/jquery.multiselect.filter.css')
						->prependStylesheet($this->basePath() . '/css/calendar/selector/jquery.multiselect.css')
						->prependStylesheet($this->basePath() . '/css/calendar/dailog.css')
						->prependStylesheet($this->basePath() . '/css/calendar/calendar.css')
						->prependStylesheet($this->basePath() . '/css/calendar/dp.css')
						->prependStylesheet($this->basePath() . '/css/calendar/alert.css')
						->prependStylesheet($this->basePath() . '/css/calendar/main.css')
						->prependStylesheet($this->basePath() . '/css/easyui.css')
        		->prependStylesheet($this->basePath() . '/css/icon.css')
						->prependStylesheet($this->basePath() . '/css/demo.css')
						//->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
						->prependStylesheet($GLOBALS['css_header'])
				?>
		
        <!-- Scripts -->
        <?php echo $this->headScript()
						//->prependFile($this->basePath() . '/js/calendar/calendar.js.php')
						
						->prependFile($this->basePath() . '/js/calendar/selector/jquery.multiselect.filter.js')
						->prependFile($this->basePath() . '/js/calendar/selector/jquery.multiselect.js')
						->prependFile($this->basePath() . '/js/calendar/jquery.calendar.js')
						->prependFile($this->basePath() . '/js/calendar/wdCalendar_lang_US.js')
						->prependFile($this->basePath() . '/js/calendar/jquery.ifrmdailog.js')
						->prependFile($this->basePath() . '/js/calendar/jquery.alert.js')
						->prependFile($this->basePath() . '/js/calendar/jquery.datepicker.js')
						->prependFile($this->basePath() . '/js/calendar/datepicker_lang_US.js')
						->prependFile($this->basePath() . '/js/calendar/Common.js')
						->prependFile($this->basePath() . '/js/lib/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
						->prependFile($this->basePath() . '/js/lib/bootstrap.min.js')
						->prependFile($this->basePath() . '/js/lib/jquery.easyui.overrider.js')
						->prependFile($this->basePath() . '/js/lib/jquery.easyui.min.js')
						->prependFile($this->basePath() . '/js/calendar/selector/jquery-ui.min.js')
						->prependFile($this->basePath() . '/js/lib/jquery-1.8.0.min.js')
						->prependFile($this->basePath() . '../../../../../library/restoreSession.php')
					?>
					
	
    </head>
    <body  class="body_top">
				<div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2013<?php echo xlt(' by ZHHealthcare');?>. <?php echo xlt('All rights reserved') ?>.</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
