<?php
// +-----------------------------------------------------------------------------+ 
// Copyright (C) 2013 Z&H Consultancy Services Private Limited <sam@zhservices.com>
//
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
//
// A copy of the GNU General Public License is included along with this program:
// openemr/interface/login/GnuGPL.html
// For more information write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
// 
// Author:   Remesh Babu S<remesh@zhservices.com>
//
// +------------------------------------------------------------------------------+
echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
          ->prependStylesheet($this->basePath() . '/css/jquery.contextMenu.css')
          ->prependStylesheet($this->basePath() . '/css/easyui.css')
          ->prependStylesheet($this->basePath() . '/css/icon.css')
          ->prependStylesheet($this->basePath() . '/css/demo.css')
          ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
          ->prependStylesheet($this->basePath() . '/css/style.css')
          ->prependStylesheet($this->basePath() . '/css/suggestion.css')
          ->prependStylesheet($this->basePath() . '/css/bubbletip-IE.css')
          ->prependStylesheet($this->basePath() . '/css/bubbletip.css')
          ->prependStylesheet($this->basePath() . '/css/bubbles.css')
          ->prependStylesheet($this->basePath() . '/css/jquery-ui.css')
          ->prependStylesheet($GLOBALS['css_header']) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/lib/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/lib/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/lib/jquery.easyui.overrider.js')
            ->prependFile($this->basePath() . '/js/lib/jquery.easyui.min.js')
            ->prependFile($this->basePath() . '/js/lib/jquery-1.8.0.min.js')
            ->prependFile($this->basePath() . '/../../../../library/dialog.js')
            ?>

    </head>
    <body  class="body_top">
	<?php echo $this->content; ?>
    </body>
</html>

