<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink()
						->prependStylesheet($this->basePath() . '/css/slider/css/slide.css')
        		->prependStylesheet($this->basePath() . '/css/easyui.css')
        		->prependStylesheet($this->basePath() . '/css/icon.css')
        		->prependStylesheet($this->basePath() . '/css/demo.css')
						->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
						->prependStylesheet($this->basePath() . '/css/style.css')
						->prependStylesheet($GLOBALS['css_header'])
						->prependStylesheet($this->basePath() . '/css/encounter.css')
				?>

        <!-- Scripts -->
        <?php echo $this->headScript()
        			->prependFile($this->basePath() . '/js/encounter/slide.js')
        			->prependFile($this->basePath() . '/js/encounter/encounter.js')
						->prependFile($this->basePath() . '/js/lib/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
						->prependFile($this->basePath() . '/js/lib/bootstrap.min.js')
						->prependFile($this->basePath() . '/js/lib/jquery.easyui.min.js')
						->prependFile($this->basePath() . '/js/lib/jquery-1.8.0.min.js')
						->prependFile($this->basePath() . '../../../../../library/restoreSession.php')
					?>
    </head>
    <body  class="body_top">
    	<div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2013<?php echo xlt(' by ZHHealthcare');?>. <?php echo xlt('All rights reserved') ?>.</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
