<?php
	// module/Acl/view/layout/layout.phtml
	echo $this->doctype(); 
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
        		->prependStylesheet($this->basePath() . '/css/acl.css')
			->prependStylesheet($this->basePath() . '/css/jquery.treeview-1.4.1/jquery.treeview.css')
			->prependStylesheet($this->basePath() . '/css/easyui.css')
                        ->prependStylesheet($this->basePath() . '/css/icon.css')
                        ->prependStylesheet($this->basePath() . '/css/demo.css')
			->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
			->prependStylesheet($this->basePath() . '/css/style.css')
			->prependStylesheet($this->basePath() . '/css/suggestion.css')
			->prependStylesheet($this->basePath() . '/css/bubbletip-IE.css')
			->prependStylesheet($this->basePath() . '/css/bubbletip.css')
			->prependStylesheet($this->basePath() . '/css/bubbles.css')
			->prependStylesheet($this->basePath() . '/css/zendlab.css')
			->prependStylesheet($this->basePath() . '/css/jquery.custom-scrollbar.css')
			->prependStylesheet($GLOBALS['css_header']) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
					->prependFile($this->basePath() . '/js/lib/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
					->prependFile($this->basePath() . '/js/lib/bootstrap.min.js')
					->prependFile($this->basePath() . '/js/acl/acl.js')
					->prependFile($this->basePath() . '/js/lib/jquery.treeview-1.4.1/jquery.treeview.js')
					->prependFile($this->basePath() . '/js/lib/jquery-ui.js')
					->prependFile($this->basePath() . '/js/lib/jquery.custom-scrollbar.js')
					->prependFile($this->basePath() . '/js/lib/jquery-1.8.0.min.js')
					?>

    </head>
    <body  class="container_body">
        <div class="container2" style="width:100%">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
