<h1><?php echo $this->escapeHtml($title); ?></h1>

<div style="margin:10px 0;"></div>
<div class="easyui-panel" title="<?php echo xlt('Procedure Order');?>" style="width:600px;">
	<div style="padding:10px 0 10px 60px">
	<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('lab', array('action' => 'index')));
	$form->prepare();
	echo $this->form()->openTag();
	//print_r($this->emr_helper()->getList("ord_priority"));
	?>
	<table>
		<tr>
			<td><?php echo xlt('Ordering Provider');?>:</td>
			<td><?php echo $this->formRow($form->get('provider'));?></td>
		</tr>
		<tr>
			<td><?php echo xlt('Sending To');?>:</td>
			<td><?php echo $this->formRow($form->get('lab_id'));?></td>
		</tr>
		<tr>
			<td><?php echo xlt('Order Date');?>:</td>
			<td><?php echo $this->formRow($form->get('orderdate'));?></td>
		</tr>
		<tr>
			<td><?php echo xlt('Internal Time Collected');?>:</td>
			<td><?php echo $this->formRow($form->get('timecollected'));?></td>
		</tr>
		<tr>
			<td><?php echo xlt('Priority');?>:</td>
			<td><?php echo $this->formRow($form->get('priority'));?></td>
		</tr>
		<tr>
			<td><?php echo xlt('Status');?>:</td>
			<td><?php echo $this->formRow($form->get('status'));?></input></td>
		</tr>
		<tr>
			<td><?php echo xlt('Diagnoses');?>:</td>
			<td><?php echo $this->formRow($form->get('diagnoses'));?></td>
		</tr>
		<tr>
			<td><?php echo xlt('Patient Instructions');?>:</td>
			<td><?php echo $this->formRow($form->get('patient_instructions'));?></td>
		</tr>
		<tr>
			<td><?php echo xlt('Procedure');?>:</td>
			<td><?php echo $this->formRow($form->get('procedures'));?></td>
		</tr>
	</table>
	<div style="text-align:center;padding:5px">
	    <a href="javascript:void(0)" class="easyui-linkbutton" onclick="submitForm()">Submit</a>
	    <a href="javascript:void(0)" class="easyui-linkbutton" onclick="clearForm()">Clear</a>
	</div>
	</div>
</div>
<?php
echo $this->form()->closeTag();
echo $this->headScript()->prependFile($this->basePath() . '/js/lab/lab.js')
					->appendFile($this->basePath() . '/js/lib/jquery.autocomplete.js')
					->appendFile($this->basePath() . '/js/lib/jquery.mockjax.js')
					->appendFile($this->basePath() . '/js/lib/jquery-1.8.2.min.js')
?>