<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('lab', array('action' => 'savedata')));
	$form->prepare();
	
	echo $this->form()->openTag($form);
	echo $this->formRow($form->get('hiddensubmit'));
	echo $this->formRow($form->get('patient_id'));
	echo $this->formRow($form->get('encounter_id'));
	echo $this->formRow($form->get('procedurecount[0][]'));
        echo $this->headScript()->prependFile($this->basePath() . '/js/lab/labOrder.js');
        echo $this->headLink()->prependStylesheet($this->basePath() . '/css/labOrder.css');
?>
<?php if ($this->message == 'N') { ?>
    <div class="easyui-accordion" style="width:auto;height:550px;">
        <div  title="<?php echo xlt('Procedur Order'); ?>" style="overflow:auto;padding:10px;">
            <div id="dlg" class="easyui-dialog" title="Basic Dialog" data-options="iconCls:'icon-save'" style="width:400px;height:200px;padding:10px">
                    Please select patient and encounter .. !
            </div>
        </div>
    </div>
<?php } else { ?>
<!--a href="#"  plain="true" onclick="newOrder();">
    <img  class="easyui-linkbutton" iconCls="icon-multiple" src=<?php echo $this->basePath() .'/css/icons/multiple.png'; ?> title=<?php echo xlt('Order'); ?> border=0 />
    <?php echo xlt('New Order'); ?>
</a-->
<a href="#"  plain="true" onclick="saveFrm();">
    <img  class="easyui-linkbutton" iconCls="icon-save" src=<?php echo $this->basePath() .'/css/icons/filesave.png'; ?> title=<?php echo xlt('Save'); ?> border=0 />
    <?php echo xlt('Save'); ?>
</a>

<div id='accord' class="easyui-accordion" style="width:auto;height:550px;">
    <div id='main_1' title="<?php echo xlt('Procedur Order'); ?>" data-options="iconCls:'icon-single'" style="overflow:auto;padding:10px;">
            <div id="toolbar_1">
                <span style="padding-left: 10px;" >
                    <a href="javascript:void(0)" id='addButton'  plain="true" onclick="addRow();">
                        <img  src=<?php echo $this->basePath() .'/css/icons/edit_add.png'; ?> title=<?php echo xlt('Add'); ?> border=0 />
                        <?php echo xlt('Add Procedure'); ?>
                    </a>
                </span>
                <span style="padding-left: 10px;" >
                    <a href="#"  plain="true" onclick="newOrder();">
                        <img  class="easyui-linkbutton" iconCls="icon-multiple" src=<?php echo $this->basePath() .'/css/icons/multiple.png'; ?> title=<?php echo xlt('Order'); ?> border=0 />
                        <?php echo xlt('New Order'); ?>
                    </a>
                </span>
            </div>
            <div id='editor_1' style="text-align: left; padding-left:20px;">
                <table id='tt_1' border='0' class="dv-table gridtable" style="width:98%;background:#fafafa;padding:1px;margin-top:5px;margin-bottom:15px;border:1px solid #95B8E7; box-shadow: 10px 10px 5px #E0E0EB;">
                    <tr style="font-weight: bold">
                        <td><?php echo xlt('Ordering Provider');?></td>
                        <td><?php echo xlt('Sending To');?></td>
                        <td><?php echo xlt('Order Date');?></td>
                        <td id="internaltimecaption_1_1" style="display:none"><?php echo xlt('Internal Time Collected');?></td>
                        <td><?php echo xlt('Internal Comments');?></td>
                        <td id='specimencollectedcaption_1_1' style="display:none"><?php echo xlt('Specimen Collected');?></td>
                        <td><?php echo xlt('Priority');?></td>
                        <td><?php echo xlt('Status');?></td>
                        <td id='billtocaption_1_1' style="display:none" valign='top'><?php echo xlt('Bill To');?></td>
                    </tr>
                    <tr>
                        <td valign='top'><?php echo $this->formRow($form->get('provider[0][]'));?></td>
                        <td valign='top'><?php echo $this->formRow($form->get('lab_id[0][]'));?></td>
                        <td valign='top'>
                            <?php echo $this->formRow($form->get('orderdate[0][]'));?>
                        </td>
                        <!--<td valign='top' id="internaltime_1_1" style="display:none">
                                <?php //echo $this->formRow($form->get('timecollected[0][]'));?>
                        </td>-->
                        <td  valign='top'><?php echo $this->formRow($form->get('internal_comments[0][]'));?></td>
                        <td valign='top' id='specimencollectedtd_1_1' style="display:none">
                            <?php echo $this->formRadio($form->get('specimencollected[0][]'), 'prepend');?>
                        </td>
                        <td valign='top'><?php echo $this->formRow($form->get('priority[0][]'));?></td>
                        <td valign='top'><?php echo $this->formRow($form->get('status[0][]'));?></td>
                        <td id='billtotd_1_1' style="display:none" valign='top'><?php echo $this->formRow($form->get('billto[0][]'));?></td>
                    </tr>
                </table>

                <table id='dgord_1' border='0'  style="width:98%;background:#fafafa;padding:5px;margin-top:5px;margin-bottom:15px;border:1px solid #95B8E7; box-shadow: 10px 10px 5px #E0E0EB;">
                    <tr>
                        <td>
                            <table class="dv-table gridtable" style="width:100%;background:#fafafa;padding:5px;">
                            <tr  style="font-weight: bold">
                                    <td width='40%' valign='top'><?php echo xlt('Patient Instructions');?></td>
                                    <td width='20%' valign='top'><?php echo xlt('Diagnoses');?></td>
                                    <td width='20%' valign='top'><?php echo xlt('Procedure');?></td>
                                    <td align='center'><?php echo xlt('Action'); ?></td>
                            </tr>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td id="insTempl_1_1">
                            <table id='cloneID_1_1' class="dv-table gridtable" style="width:100%;background:#fafafa;padding:5px;">
                            <tr >
                                    <td width='40%' valign='top'><?php echo $this->formRow($form->get('patient_instructions[0][]'));?></td>
                                    <td width='20%' valign='top'>
                                        <span id="diagnosestemplate_1_1">
                                            <?php echo $this->formRow($form->get('diagnoses[0][]'));?>
                                            <div class="autocomplete-suggestions" id="diagnodiv_1_1" style="display:none;z-index:99999;position:absolute;min-width:150px"></div>
                                        </span>
                                    </td>
                                    <td width='20%' valign='top'>
                                        <span id="proceduretemplate_1_1">
                                            <?php echo $this->formRow($form->get('procedures[0][]'));?>
                                            <div class="autocomplete-suggestions" id="prodiv_1_1" style="display:none;z-index:99999;position:absolute;min-width:150px"></div>
                                            <?php echo $this->formRow($form->get('procedure_code[0][]'));?>
                                             <?php echo $this->formRow($form->get('procedure_suffix[0][]'));?>
                                        </span>
                                    </td>
                                    <td valign='top' align='center'>
                                        <span style="padding-left: 10px;" >
                                            <a href="#" id='deleteButton_1_1'  style="height: 20px;"  plain="true" onclick="cancelItem(this.id)">
                                                <img  class="easyui-linkbutton" iconCls="icon-cancel" src=<?php echo $this->basePath() .'/css/icons/cancel.png'; ?> title=<?php echo xlt('Cancel'); ?> border=0 />
                                                <?php echo xlt('Cancel'); ?>
                                            </a>
                                        </span>
                                        <span style="padding-left: 10px;" >
                                            <a href="javascript:void(0)" id='addButton_1_1'  plain="true" onclick="addRow();">
                                                <img  src=<?php echo $this->basePath() .'/css/icons/edit_add.png'; ?> title=<?php echo xlt('Add'); ?> border=0 />
                                                <?php echo xlt('Add'); ?>
                                            </a>
                                        </span>
                                    </td> 
                            </tr>
                            <tr id="AOEtemplate_1_1"  style="display:none">
                                    <!--<td>&nbsp;</td>
                                    <td>&nbsp;</td>
                                    <td>&nbsp;</td>-->
                                    <td id="AOE_1_1" colspan='4'></td>
                            </tr>
                            </table>
                        </td>
                    </tr>
                </table><!-- End dgord-->
           </div><!-- End editor -->
    </div><!-- End main -->
  
</div><!-- End accord -->

<?php
        }
        echo $this->form()->closeTag();
	echo $this->headScript()//->prependFile($this->basePath() . '/js/lib/jquery-1.8.2.min.js')
				->prependFile($this->basePath() . '/js/lab/lab.js')
				->prependFile($this->basePath() . '/js/lib/jquery.autocomplete.js')
				->prependFile($this->basePath() . '/js/lib/jQuery.bubbletip-1.0.6.js')
				->prependFile($this->basePath() . '/js/lib/bubbles.js')
?>
<!-- Start Row Template -->
<div style="display:none" id="procedureclonetemplate">
<table  id='cloneID_1' class="dv-table gridtable" style="width:100%;background:#fafafa;padding:5px;">
<tr>
        <td width='40%' valign='top'><?php echo $this->formRow($form->get('patient_instructions[0][]'));?></td>
        <td width='20%' valign='top'>
            <span id="diagnosestemplate">
                <?php echo $this->formRow($form->get('diagnoses[0][]'));?>
                <div class="autocomplete-suggestions" id="diagnodiv" style="display:none;z-index:99999;position:absolute;min-width:150px"></div>
            </span>
        </td>
        <td width='20%' valign='top'>
            <span id="proceduretemplate">
                <?php echo $this->formRow($form->get('procedures[0][]'));?>
                <div class="autocomplete-suggestions" id="prodiv" style="display:none;z-index:99999;position:absolute;min-width:150px"></div>
                <?php echo $this->formRow($form->get('procedure_code[0][]'));?>
                 <?php echo $this->formRow($form->get('procedure_suffix[0][]'));?>
            </span>
        </td>
        <td valign='top' align='center'>
            <span style="padding-left: 10px;" >
                <a href="#" id='deleteButton'  style="height: 20px;"  plain="true" onclick="cancelItem(this.id)">
                    <img  class="easyui-linkbutton" iconCls="icon-cancel" src=<?php echo $this->basePath() .'/css/icons/cancel.png'; ?> title=<?php echo xlt('Cancel'); ?> border=0 />
                    <?php echo xlt('Cancel'); ?>
                </a>
            </span>
            <span style="padding-left: 10px;" >
                <a href="javascript:void(0)" id='addButton'  plain="true" onclick="addRow();">
                    <img  src=<?php echo $this->basePath() .'/css/icons/edit_add.png'; ?> title=<?php echo xlt('Add'); ?> border=0 />
                    <?php echo xlt('Add'); ?>
                </a>
            </span>
        </td> 
</tr>
<tr id="AOEtemplate"  style="display:none">
        <!--<td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>-->
        <td id="AOE" colspan='4'></td>
</tr>
</table>
</div>
<!-- End Row Template -->

<!-- Start New Order Template -->
<div style="display:none" id="newprocedureclonetemplate">
<div id='mainTemplate'>
    <div id='main' title="<?php echo xlt('Procedur Order'); ?>" data-options="iconCls:'icon-single'" style="overflow:auto;padding:10px;">
            <div id="toolbar">
                <span style="padding-left: 10px;" >
                    <a href="javascript:void(0)" id='addButton'  plain="true" onclick="addRow();">
                        <img  src=<?php echo $this->basePath() .'/css/icons/edit_add.png'; ?> title=<?php echo xlt('Add'); ?> border=0 />
                        <?php echo xlt('Add Procedure'); ?>
                    </a>
                </span>
                <span style="padding-left: 10px;" >
                    <a href="#"  plain="true" onclick="newOrder();">
                        <img  class="easyui-linkbutton" iconCls="icon-multiple" src=<?php echo $this->basePath() .'/css/icons/multiple.png'; ?> title=<?php echo xlt('Order'); ?> border=0 />
                        <?php echo xlt('New Order'); ?>
                    </a>
                </span>
                <span style="margin-left: 70%;">
                    <a href="javascript:void(0)"  onclick="removeAccord()">
                        <img  class="easyui-linkbutton" iconCls="icon-no" src=<?php echo $this->basePath() .'/css/icons/no.png'; ?> title=<?php echo xlt('Remove Order'); ?> border=0 />
                        <?php echo xlt('Remove Order'); ?>
                    </a>
                </span>
            </div>
            <div id='editor' style="text-align: left; padding-left:20px;">

                <table id='tt' border='0' class="dv-table gridtable" style="width:98%;background:#fafafa;padding:1px;margin-top:5px;margin-bottom:15px;border:1px solid #95B8E7; box-shadow: 10px 10px 5px #E0E0EB;">
                    <tr style="font-weight: bold">
                        <td><?php echo xlt('Ordering Provider');?></td>
                        <td><?php echo xlt('Sending To');?></td>
                        <td><?php echo xlt('Order Date');?></td>
                        <td id='internaltimecaption' style="display:none" style="display:none"><?php echo xlt('Internal Time Collected');?></td>
                        <td><?php echo xlt('Internal Comments');?></td>
                        <td id='specimencollectedcaption' style="display:none" ><?php echo xlt('Specimen Collected');?></td>
                        <td><?php echo xlt('Priority');?></td>
                        <td><?php echo xlt('Status');?></td>
                        <td id='billtocaption' style="display:none" valign='top'><?php echo xlt('Bill To');?></td>
                    </tr>
                    <tr>
                        <td valign='top'><?php echo $this->formRow($form->get('provider[0][]'));?></td>
                        <td valign='top'><?php echo $this->formRow($form->get('lab_id[0][]'));?></td>
                        <td valign='top' id="oderingdate"><?php echo $this->formRow($form->get('orderdate[0][]'));?></td>
                        <td valign='top' id="internaltime" style="display:none"><?php echo $this->formRow($form->get('timecollected[0][]'));?></td>
                        <td  valign='top'><?php echo $this->formRow($form->get('internal_comments[0][]'));?></td>
                        <td id='specimencollectedtd' style="display:none" valign='top'><?php echo $this->formRadio($form->get('specimencollected[0][]'), 'prepend');?></td>
                        <td valign='top'><?php echo $this->formRow($form->get('priority[0][]'));?></td>
                        <td valign='top'><?php echo $this->formRow($form->get('status[0][]'));?></td>
                        <td id='billtotd' style="display:none" valign='top'><?php echo $this->formRow($form->get('billto[0][]'));?></td>
                    </tr>
                </table>

                <table id='dgord' border='0'  style="width:98%;background:#fafafa;padding:5px;margin-top:5px;margin-bottom:15px;border:1px solid #95B8E7; box-shadow: 10px 10px 5px #E0E0EB;">
                    <tr>
                        <td>
                            <table class="dv-table gridtable" style="width:100%;background:#fafafa;padding:5px;">
                            <tr  style="font-weight: bold">
                                    <td width='40%' valign='top'><?php echo xlt('Patient Instructions');?></td>
                                    <td width='20%' valign='top'><?php echo xlt('Diagnoses');?></td>
                                    <td width='20%' valign='top'><?php echo xlt('Procedure');?></td>
                                    <td align='center'><?php echo xlt('Action'); ?></td>
                            </tr>
                            </table>
                        </td>
                    </tr>
                    <!-- -->
                    <tr>
                        <td id="insTempl">
                        
                        </td>
                    </tr>
                    <!-- -->
                </table><!-- End dgord-->
           </div><!-- End editor -->
    </div><!-- End main -->
</div>
</div>
<!-- End New Order Template -->