<form method="post">
	<table class="dv-table" style="width:100%;background:#fafafa;padding:5px;margin-top:5px;">
		<tr>
			<td>Date</td>
			<td><input name="date_ordered" class="easyui-validatebox" ></input></td>
			<td>Provider</td>
			<td><input name="provider_id" class="easyui-validatebox"></input></td>
		</tr>
		<tr>
			<td>Patient</td>
			<td><input name="patient_id"></input></td>
			<td>Encounter</td>
			<td><input name="encounter_id" class="easyui-validatebox"></input></td>
		</tr>
	</table>
	<div style="padding:5px 0;text-align:right;padding-right:30px">
		<a href="#" class="easyui-linkbutton" iconCls="icon-save" plain="true" onclick="saveItem(<?php echo $_REQUEST['index'];?>)">Save</a>
		<a href="#" class="easyui-linkbutton" iconCls="icon-cancel" plain="true" onclick="cancelItem(<?php echo $_REQUEST['index'];?>)">Cancel</a>
	</div>
</form>