<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="<?php echo  $GLOBALS['css_header'];?>" type="text/css">
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
		<?php echo $this->headLink()
                        ->prependStylesheet($this->basePath() . '/css/emr.css')
                       ?>
		
        <!-- Scripts -->
        <?php 	echo $this->headScript()->prependFile($this->basePath() .'/js/lib/jquery-1.7.2.min.js') 
        ?>

    </head>
    <body class="body_top">
        <div class="container">
            <?php echo $this->content; ?>           
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
