<?php 
// +-----------------------------------------------------------------------------+ 
// Copyright (C) 2013 Z&H Consultancy Services Private Limited <sam@zhservices.com>
//
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
//
// A copy of the GNU General Public License is included along with this program:
// openemr/interface/login/GnuGPL.html
// For more information write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
// 
// Author:   Jacob T.Paul <jacob@zhservices.com>
//
// +------------------------------------------------------------------------------+
echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
        		->prependStylesheet($this->basePath() . '/css/easyui.css')
                        ->prependStylesheet($this->basePath() . '/css/icon.css');
echo $this->headScript()->appendFile($this->basePath() . '/js/installer/action.js')
                        ->appendFile($this->basePath() . '/js/lib/jquery.easyui.min.js')
                        ->appendFile($this->basePath() . '/js/lib/jquery-1.7.2.min.js');
$title = xlt('Module Installer');
$this->headTitle($title);
$baseModuleDir 	= $GLOBALS['baseModuleDir'];
$customDir 	= $GLOBALS['customDir'];
$zendModDir 	= $GLOBALS['zendModDir'];
if(count($TabSettings)>0){
?>
<div class="easyui-tabs" style="width:800px;height:auto;">
    <?php
    if($TabSettings[1]['cnt'] > 0){
    ?>
    <div title="ACL" iconCls="icon-acl">
        <form name="aclform" id="aclform">
        <div class="easyui-accordion" style="width:787px;height:auto;align:center;margin:5px">
    <?php foreach($ACL as $obj_acl){ ?>
        <div title="<?php echo xlt($obj_acl->menu_name);?>" style="overflow:auto;padding:10px;">
            <table>
            <select name="<?php echo $obj_acl->obj_name;?>[]" multiple="multiple" size="5">
                <?php
                foreach($ListActiveUsers as $k=>$v){
                ?>
                <option value="<?php echo $k;?>"><?php echo $v;?></option>
                <?php
                }
                ?>
            </select>
            </table>
        </div>
        <?php
    }
    ?>
        </div>
        <div style="text-align:center"><a href="#" class="easyui-linkbutton" iconCls="icon-save" plain="true" onclick="javascript:SaveMe('aclform')"><?php echo xlt('Save'); ?></a></div>
        </form>
    </div>
    <?php
    }
    if($TabSettings[2]['cnt'] > 0){
    ?>
    <div title="Preference" iconCls="icon-preference">  
        Second Tab  
    </div>
    <?php
    }
    if($TabSettings[3]['cnt'] > 0){
    ?>
    <div title="Hooks" iconCls="icon-plug"> 
        Third Tab  
    </div>
    <?php
    }
    ?>
</div>
<?php
}
?>