<?php 
// +-----------------------------------------------------------------------------+ 
// Copyright (C) 2013 Z&H Consultancy Services Private Limited <sam@zhservices.com>
//
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
//
// A copy of the GNU General Public License is included along with this program:
// openemr/interface/login/GnuGPL.html
// For more information write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
// 
// Author:   Jacob T.Paul <jacob@zhservices.com>
//           Eldho Chacko <eldho@zhservices.com>
//
// +------------------------------------------------------------------------------+

$title = xlt('Module Installer');
$this->headTitle($title);
$baseModuleDir 	= $GLOBALS['baseModuleDir'];
$customDir 	= $GLOBALS['customDir'];
$zendModDir 	= $GLOBALS['zendModDir'];
$confirmationMSG = xlt("Do you really want to delete?");
if(count($TabSettings)>0){
?>
<div class="easyui-tabs" id="tab" style="width:800px;height:auto;">
    <div title="<?php echo xlt('Settings');?>" id="tab_settings" iconCls="icon-preference">
        <form name="settingsform" id="settingsform">
          <?php foreach($Modules as $obj_modules){ ?>
          <table>
            <tr>
              <td>
                <?php echo xlt("Nick Name");?>
              </td>
              <td>
                <input type="hidden" name="mod_id" value="<?php echo $mod_id;?>">
                <input type="text" name="nickname" value="<?php echo $obj_modules->modnickname;?>">
              </td>
            </tr>
          </table>
          <?php } ?>
        <div style="text-align:center"><a href="#" class="easyui-linkbutton" iconCls="icon-save" plain="true" onclick="javascript:SaveMe('settingsform',<?php echo $mod_id;?>)"><?php echo xlt('Save'); ?></a></div>
        </form>
    </div>
    <?php
    if($TabSettings[1]['cnt'] > 0){
    ?>
    <div title="<?php echo xlt('ACL');?>" id="tab_acl" iconCls="icon-acl">
        <form name="aclform" id="aclform">
        <div class="easyui-accordion" id="configaccord" style="width:787px;height:auto;align:center;margin:5px">
    <?php foreach($ACL as $obj_acl){ ?>
        <div title="<?php echo xlt($obj_acl->menu_name);?>" style="overflow:auto;padding:10px;">
        <table>
            <tr>
              <td>
                <?php echo xlt("Add New ACL");?>
              </td>
              <td>
                <?php echo xlt("Saved ACL");?>
              </td>
            </tr>
            <tr>
                <td>
                    <table>
                    <select name="modules_<?php echo strtolower($obj_acl->mod_directory)."_-_-_".$obj_acl->obj_name;?>[]" multiple="multiple" size="5">
                        <?php
                        foreach($ListActiveUsers as $k=>$v){
                        ?>
                        <option value="<?php echo $k;?>"><?php echo xlt($v);?></option>
                        <?php
                        }
                        ?>
                    </select>
                    </table>
                </td>
                <td>
                    <table border="0">
                        <?php
                        foreach($ListActiveACL[$obj_acl->obj_name] as $k=>$ActiveACL){
                        ?>
                        <tr>
                            <td><?php echo $ActiveACL['user'];?>
                            </td>
                            <td>
                              <a href="#"  onclick="javascript:DeleteACL(<?php echo $ActiveACL['acl_id'];?>,'<?php echo $ActiveACL['value'];?>',<?php echo $mod_id;?>,'<?php echo $confirmationMSG;?>')"><div class="icon-cancel" style="width:20px">&nbsp;</div></a>
                            </td>
                        </tr>
                        <?php
                        }
                        ?>
                    </table>
                </td>
            </tr>
        </table>
        </div>
        <?php
    }
    ?>
        </div>
        <div style="text-align:center"><a href="#" class="easyui-linkbutton" iconCls="icon-save" plain="true" onclick="javascript:SaveMe('aclform',<?php echo $mod_id;?>)"><?php echo xlt('Save'); ?></a></div>
        </form>
    </div>
    <?php
    }
    if($TabSettings[2]['cnt'] > 0){
    ?>
    <div title="<?php echo xlt('Preference');?>" id="tab_preference" iconCls="icon-preference">  
        <!-- For Future Development-->
    </div>
    <?php
    }
    if($TabSettings[3]['cnt'] > 0){
      $modID = '';
    ?>
    <div title="<?php echo xlt('Hooks');?>" id="tab_hooks" iconCls="icon-plug" > 
      <table>
            <tr>
              <td colspan="2" align="center">
                <?php echo xlt("Add New Hooks");?>
              </td>
            </tr>
            <tr>
                <td>
                  <form name="hooksform" id="hooksform">
                    <table>
                      <tr>
                        <td>
                          <select name="Hooks">
                              <?php foreach($Hooks as $obj_hooks){ 
                              ?>
                              <option value="<?php echo $obj_hooks->obj_name;?>"><?php echo xlt($obj_hooks->menu_name);?></option>
                              <?php
                              }
                              ?>
                          </select>
                        </td>
                        <td>
                          <select name="AttachedTo">
                            <option value="reports"><?php echo xlt("Reports");?></option>
                            <option value="encounter"><?php echo xlt("Encounter");?></option>
                          </select>
                        </td>
                        <td>
                          <a href="#" class="easyui-linkbutton" iconCls="icon-save" plain="true" onclick="javascript:SaveMe('hooksform',<?php echo $mod_id;?>)"><?php echo xlt('Save'); ?></a>
                        </td>
                      </tr>
                    </table>
                    <input type="hidden" name="mod_id" value="<?php echo $mod_id;?>">
                  </form>
                </td>
            </tr>
            <tr>
              <td colspan="2" align="center">
                <?php echo xlt("Saved Hooks");?>
              </td>
            </tr>
            <tr>
              <td>
                <table>
                  <tr>
                    <td><?php echo xlt("Hooks");?></td>
                    <td><?php echo xlt("Attached To");?></td>
                    <td><?php echo xlt("Action");?></td>
                  </tr>
                  <?php
                  foreach($ListActiveHooks as $hookslist){?>
                  <tr>
                    <td style="color:blue"><?php echo xlt($hookslist->menu_name);?></td>
                    <td style="color:blue"><?php echo ucwords(xlt($hookslist->attached_to));?></td>
                    <td style="display:inline">
                      <a href="#"  onclick="javascript:DeleteHooks(<?php echo $hookslist->id;?>,<?php echo $mod_id;?>,'<?php echo $confirmationMSG;?>')"><div class="icon-cancel" style="width:20px;float:left">&nbsp;</div></a>
                    </td>
                  </tr>
                  <?php
                  }
                  ?>
                </table>
              </td>
            </tr>
        </table>
    </div>
    <?php
    }
    ?>
</div>
<?php
}
?>