<?php 
// module/Installer/view/Installer/Installer/index.phtml:
echo $this->headScript()->appendFile(
		$this->basePath() . '/js/installer/action.js',
		'text/javascript'
);
$title = 'Module Installer';
$this->headTitle($title);
$baseModuleDir 	= $GLOBALS['baseModuleDir'];
$customDir 		= $GLOBALS['customDir'];
$zendModDir 	= $GLOBALS['zendModDir'];

?>
<h1><img src="<?php echo $this->basePath()?>/images/module.png" class="nav-menu-img"><?php echo $this->escapeHtml($title); ?></h1>

<ul class="tabNav">
		<li class="current divMenu" onclick="$('.registered').show();$('.unregistered').hide();$('.divMenu').removeClass('current');$(this).addClass('current');" >
			<a href="javascript:void(0)" id="header_tab_.htmlspecialchars(Registered,ENT_QUOTES).">
               Registered
            </a>
		</li>
	  	<li class="divMenu"  onclick="$('.registered').hide();$('.unregistered').show();$('.divMenu').removeClass('current');$(this).addClass('current');">
			<a href="javascript:void(0)" id="header_tab_.htmlspecialchars(UnReg,ENT_QUOTES).">
               Unregistered <span id='ct'></span>
            </a>
		</li>
</ul>
<div class="installer" >
	<div id='err' class='bold '></div>
	<div class="installer_code notranslate registered">			
		<form method=POST action ='./modules_admin.php'<?php echo $formtarget; ?>>
		<?php //REGISTERED SECTION ?>
			<div class="imagetable">
				<div class="imagetable_code notranslate">
					<table id="table-6" class="imagetable" align="center">
						<thead>  
							<tr>
								<th colspan='6' class="groupReg">
									Registered Modules
								</th>
							<tr>
							<tr >
								<th scope="col" ><?php xl('Sl.No ','e'); ?></th>
							    <th scope="col" ><?php xl('Module ','e'); ?> </th>
								<th scope="col" ><?php xl('Status ','e'); ?> </th>
								<th scope="col" ><?php xl('Menu Text ','e'); ?> </th>
								<th scope="col" ><?php xl('Type ','e'); ?> </th>			
								<th scope="col" ><?php xl('Action ','e'); ?> </th>						
							</tr>
					  </thead>
					<?php
					/******** Module Creation ********/
					 $count = 0;
					 if(sizeof($InstallersAll) > 0)
					    foreach ($InstallersAll as $moduleResult) {  
							$count++;
						?>
					     	<tr  id="<?php echo $moduleResult -> modId;?>">
								<td  ><?php echo $count;?>	</td>
								<td  ><?php echo xl_form_title($moduleResult -> modName); ?></td>
								<td  >
									<?php					
		 
			  							if ($moduleResult -> sqlRun==0){?>
			  								Not Installed
			  							<?php 			  								
			  							}else if ($moduleResult -> modActive == 1){?>
			  								Active
										<?php }
										else{?>
											Inactive
										<?php //echo "<img src='images/inactive.gif' width='12' height='12' border='0'/> <a  href='./manage.php?id={$moduleResult -> modId}&method=disable'$formtarget>".xl('Inactive')."</a>";
										}
									?>		
			  					</td>
								<td >
								  <?php echo xl_form_title($moduleResult -> modUiName); ?>
								</td>	
								<td>
									<?php echo xl_form_title(($moduleResult -> type == 1)? "Zend" : "Custom");?>
								</td>
								<td>
								<?php					
		 
			  							if ($moduleResult -> sqlRun==0){?>
			  								<a href="javascript:void(0)" class="link_submit install" onclick="manage('<?php echo $moduleResult -> modId?>','install');" title="Click Here to Install This module"><input type='button' class='activate' value='Install'/></a>
			  							<?php 			  								
			  							}else if ($moduleResult -> modActive == 1){?>
			  								<a href="javascript:void(0)" class="link_submit active" onclick="manage('<?php echo $moduleResult -> modId?>','enable');" title="Click Here to Disable This module"><input type='button' class='deactivate' value='Disable'/></a>
										<?php }
										else{?>
											<a href="javascript:void(0)" class="link_submit inactive" onclick="manage('<?php echo $moduleResult -> modId?>','disable');" title="Click Here to Enable This module"><input type='button' class='activate' value='Activate'/></a>
										<?php //echo "<img src='images/inactive.gif' width='12' height='12' border='0'/> <a  href='./manage.php?id={$moduleResult -> modId}&method=disable'$formtarget>".xl('Inactive')."</a>";
										}?>
								</td>
							</tr>
					<?php							
							}
						 //end of if & while
					?>
					</table>
				</div>
			</div>
			
		</form>				
	</div>
	<div class="installer_code notranslate unregistered" style="display:none">			
		<table class="imagetable" id="unregistered">
			<tr>
				<th colspan='4' class="groupRegUn">
					Unregistered Modules
				</th>
			<tr>
				<th scope="col" >Sl.No</th>
				<th scope="col" >Module Name</th>
				<th scope="col" >Type</th>
				<th scope="col" >Action</th>
			</tr>
			<?php
				$dpath = $GLOBALS['srcdir']."/../{$baseModuleDir}{$customDir}/";
				$dp = opendir($dpath);
				$inDir = array();
				for ($i=0; false != ($fname = readdir($dp)); $i++){

					if ($fname != "." && $fname != ".." && $fname != "Application" && is_dir($fname))
						$inDir[$i] = $fname;
				}
				if (sizeof($InstallersExisting) > 0){
					foreach ( $InstallersExisting as $modules ){
						 $key = "";
						 $key = array_search($modules -> modDirectory, $inDir) ;  /* returns integer or FALSE */
						 if($key != "")
						 	unset($inDir[$key]);
					}
				}				
				$slno=0;
				foreach ( $inDir as $fname ){
					$slno++;
					?>
					<tr>
						<td><?php echo $slno;?> </td>
						<td>
	        			<?php
	                		$form_title_file = @file($GLOBALS['srcdir']."/../{$baseModuleDir}{$customDir}/$fname/info.txt");
				            if ($form_title_file)						
	                        	$form_title = $form_title_file[0];
	                        else
	                            $form_title = $fname;
	                		echo xl_form_title($form_title); 
                		?>		
                		</td>						
						<td>
							Normal
						</td>	
						<td >
						 <a href="javascript:void(0)" onclick="register(1,'<?php echo xl_form_title($form_title);?>','<?php echo $fname?>','register','');"><input type='button' class='activate' value='Register'/></a>
						</td>	
					</tr>
					<?php								
					flush();
				}//end of foreach
				$dpath 	= $GLOBALS['srcdir']."/../{$baseModuleDir}{$zendModDir}/module";
				$dp 	= opendir($dpath);				
				$inDir = array();
				for ($i=0; false != ($fname = readdir($dp)); $i++){
					if ($fname != "." && $fname != ".." && ($fname != "Application" && $fname != "Installer") && is_dir($fname))
						$inDir[$i] = $fname;
				}
				if (sizeof($InstallersExisting) > 0){
					foreach ( $InstallersExisting as $modules ){
						 $key = "";
						 $key = array_search($modules -> modDirectory, $inDir) ;  /* returns integer or FALSE */
						 if($key != "")
						 	unset($inDir[$key]);
					}
				}							
				foreach ( $inDir as $fname ){
					$slno++;
					?>
					<tr>
						<td ><?php echo $slno;?> </td>
						<td > 
	        			<?php
	                		$form_title_file = @file($GLOBALS['srcdir']."/../{$baseModuleDir}{$zendModDir}/$fname/info.txt");
				            if ($form_title_file)						
	                        	$form_title = $form_title_file[0];
	                        else
	                            $form_title = $fname;
	                		echo xl_form_title($form_title); 
                		?>		
                		</td>
                		<td >
							Zend Module
						</td>	
						<td >
							<a href="javascript:void(0)" onclick="register(1,'<?php echo xl_form_title($form_title);?>','<?php echo $fname?>','register','zend');"><input type='button' class='activate' value='Register'/></a>
						</td>							
					</tr>
					<?php					
					flush();
				}//end of foreach
			?>
			
		</table>
	</div>
</div>
<?php 
if($slno > 0){
?>
<script>
	$('#ct').html('(<?php echo $slno ?>)');
</script>
<?php 
}?>