<style>
table.gridview2 td{
		border-style: dotted;
		border-width: 1px 1px 1px 1px;
		margin: 0;padding: 0;
		border-color:#cccccc;
}
table.thcolor th{
		background:linear-gradient(to bottom, #EFF5FF 0px, #E0ECFF 100%) repeat-x scroll 0 0 transparent;
		border: 1px solid #cccccc;
		height:10px;
		height:20px; 
}
#patdiv{
		position: absolute;
		left: 460px;
		border: 1px solid #95B8E7;
		display: none;
		min-width: 143px;
		background-color: #fff;
		margin: 0 6px;
}
</style>
<script type="text/javascript">
$(document).ready(function (){
		<?php if($this->layout()->saved == 'yes'){ ?>
		alert('Successfully Saved');
		<?php } ?>
});
function doSearch(){
		if($("#search_patient").val() == ''){
				$("#patient_id").val('');
		}
		$("#specimen").submit();
}
function doSave(){
		$("#specimen").attr("action", window.location.href.replace("index","save"));
		$("#specimen").submit();
}
</script>
<div style="margin:10px 0;"></div>
<div class="easyui-panel" title="<?php echo xlt('Sample Collection');?>" >
	<div style="padding:10px;">
		<?php
		$form = $this->form;
		$form->setAttribute('action', $this->url('specimen', array('action' => 'index')));
		$form->prepare();
		
		echo $this->form()->openTag($form);
		?>
		<div>
				<div>
						<span class="bold mediumfont" >Date</span>
				</div>
				<div style="float:left;padding-right:10px;">
						<span><?php echo xlt('From').":&nbsp;"; echo $this->formRow($form->get('search_from_date')); ?></span>
						<span><?php echo xlt('To').":&nbsp;"; echo $this->formRow($form->get('search_to_date')); ?></span>
						<span style="padding-left:25px;"><?php echo xlt('Patient').":&nbsp;"; echo $this->formRow($form->get('search_patient')); ?></span>
						<div id="patdiv" ></div>
						<?php echo $this->formRow($form->get('patient_id')); ?>
				</div>
				<a href="#" class="easyui-linkbutton" iconCls="icon-search" plain="true" onclick="doSearch()"><?php echo xlt('Search'); ?></a>
		</div>
		<br/>
		<a href="#" class="easyui-linkbutton" iconCls="icon-save" plain="true" onclick="doSave()"><?php echo xlt('Save'); ?></a>
		<table id="specimentable" class="dv-table gridview2 thcolor" style="width:99%;height:auto;background:#ffffff;padding:5px;margin-top:5px;margin-bottom:15px;" >
			<tr>
					<th colspan="4" class="mainhead" >Order</th>
					<th colspan="3" class="mainhead" >Report</th>
			</tr>
			<tr>
					<td style="width:40px;" >PID</td>
					<td style="min-width:80px;" >Patient Name</td>
					<td style="width:80px;" >Order Date</td>
					<td style="min-width:200px;" >Name</td>
					<td >Specimen</td>
					<td >Specimen Time Collected</td>
					<td >Specimen Status</td>
			</tr>
			<?php foreach($this->layout()->res as $val): ?>
			<tr>
				<td><?php echo $val['patient_id']; ?></td>
				<td><?php echo $val['pname']; ?></td>
				<?php echo $this->formRow($form->get('procedure_order_id[]')->setValue($val['poid'])); ?>
				<td><?php echo $val['date_ordered']; ?></td>
				<td><?php echo $val['procedure_name']; ?></td>
				<td><?php echo $this->formRow($form->get('specimen[]')->setValue($val['specimen_num'])); ?></td>
				<td><?php echo $this->formRow($form->get('specimen_collected_time[]')->setValue($val['date_collected'])); ?></td>
				<td><?php echo $this->formRow($form->get('specimen_status[]')->setValue($val['report_status'])); ?></td>
			</tr>
			<?php endforeach; ?>
		</table>
  </div>
</div>
<?php
echo $this->form()->closeTag();
echo $this->headScript()->prependFile($this->basePath() . '/js/lib/jquery-1.8.2.min.js')
			->prependFile($this->basePath() . '/js/lab/patient.js')
			->prependFile($this->basePath() . '/js/lib/jquery.autocomplete.js')
			->prependFile($this->basePath() . '/js/lib/jQuery.bubbletip-1.0.6.js')
			->prependFile($this->basePath() . '/js/lib/bubbles.js')
?>