<?php
$listener			= $this->listenerObject;
?>
<script type="text/javascript">
    var ajax_path = "<?php echo $GLOBALS['webroot']; ?>/interface/modules/zend_modules/public/acl/ajax";
    $(document).ready(function(){
        <?php if($this->component_id != ''){?>
            selectThis("<?php echo $this->component_id; ?>");
            selected_component = "<?php echo $this->component_id; ?>";
            rebuild();
	<?php } ?>
    });
</script>
<div id="add_new_components" class="popup_items" >
    <center><div class="head"><?php echo$listener->zht('Add New Components'); ?></div></center>
    <table align="center">
	<tr>
	    <td><?php echo$listener->zht('Module'); ?></td>
	    <td>
		<select id="add_component_mod_id" onchange="getSectionById(this.value);">
		    <option value=''></option>
		    <?php
		    foreach($this->active_modules as $mod_id => $mod_name) :
		    ?>
			<option value="<?php echo $mod_id;?>"><?php echo $mod_name;?></option>
		    <?php
		    endforeach
		    ?>
		</select>
	    </td>
	</tr>
	<tr>
	    <td><?php echo$listener->zht('Parent'); ?></td>
	    <td>
		<select id="add_component_section_id"></select>
	    </td>
	</tr>
	<tr>
	    <td><?php echo$listener->zht('Section ID'); ?></td>
	    <td>
		<input id="add_component_section_identifier" type="text">
	    </td>
	</tr>
	<tr>
	    <td><?php echo$listener->zht('Parent'); ?></td>
	    <td>
		<input id="add_component_section_name" type="text">
	    </td>
	</tr>
	<tr>
	    <td colspan="2" style="text-align: right;"><a href="#" onclick="addSectionSave();" class="myButton" title="Add New Component"><?php echo$listener->zht('Add'); ?></a></td>
	</tr>
	<tr>
	    <td colspan="2" style="text-align: right;"><span id="add_component_section_message" style="color: #3AA845;"></span></td>
	</tr>
    </table>
</div>
<div style="display: none;"><div id="control_div"><a href="#" ><?php echo$listener->zht('Collapse All'); ?></a>|<a href="#" id="expand_tree"><?php echo$listener->zht('Expand All'); ?></a></div></div>
<center><div class="scrollable default-skin" style="width: 750px;height: 600px;">
    <table id="outer_table" align="center" >
        <tr>
            <td>
                    <!--contents-->
		    <span id="messages"></span>
                    <table style="width:100%;" cellspacing='5'>
    <!--                        <tr>
                                    <td colspan="4" class="container_head">ACL</td>
                            </tr>-->
			    <tr>
                                    <td colspan="4" class="delete_droppable"></td>
                            </tr>
                           <!-- <tr>
                              <td style="border: solid 1px #305A99;background-color:#E0ECFF;" colspan="4" class="container_top">
                                <span id="messages"></span>
                              </td>
                            </tr>-->
                            <tr style="height: 30px;"> 
                                    <td style="border: solid 1px #305A99" class="container head">Components &nbsp;<?php if(!$this->module_id) {?><a href="#" onclick="addNewItem('components');" class="myButton" title="Add New Component"><?php echo$listener->zht('Add'); ?></a><?php } ?>
				    </td>
                                    <td style="border: solid 1px #305A99" class="container head"><?php echo$listener->zht('Group/Users'); ?></td>
                                    <td style="border: solid 1px #2A6614;background-color:#E4F7CD;" class="container head"><?php echo$listener->zht('Allowed'); ?></td>
                                    <td style="border: solid 1px #B32317;background-color:#F9C7C7;" class="container head"><?php echo$listener->zht('Denied'); ?></td>
                            </tr>
                            <tr style="height: 50px;"> 
                                    <td class="container_div" id="td_componets" style="background-color:#E0ECFF;border: solid 1px #305A99">
                                        <?php echo $this->sections; ?>
                                    </td>
                                    <td class="container_div" id="td_users" style="background-color:#E0ECFF;border: solid 1px #305A99;">
                                            <?php echo $this->user_group_main; ?>
                                    </td>
                                    <td style="border: solid 1px #2A6614;background-color:#E4F7CD;" class="container_div droppableAllowed" id="td_allowed_users"><?php echo $this->user_group_allowed; ?></td>
                                    <td style="border: solid 1px #B32317;background-color:#F9C7C7;" class="container_div droppableDenied" id="td_denied_users"><?php echo $this->user_group_denied; ?></td>
                            </tr>
                            <tr>
                                    <td colspan="4" class="delete_droppable"></td>
                            </tr>
                    </table>
                    <!--contents--> 
            </td>
        </tr>
    </table>
</div></center>